import { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { useWarehouseReturns } from '../WarehouseReturns/useWarehouseReturns';
import useWarehouseParams from '../shared/useWarehouseParams';
import { isAutoGeneratedSystemBatch } from '@shared/utils/dilovodBatchId';
import type {
  EnsureInventorySetResult,
  FillBatchesResult,
  KitOutputBatchInfo,
  ReleaseComponentAllocation,
  ReleaseComponentBatch,
  ReleaseLastKitBatchesResponse,
  ReleasePreviewComponent,
} from '@shared/types/warehouseRelease';
import { buildRebatchSku, isRebatchSku } from '@shared/types/warehouseRelease';
import { formatCorrectionBatchDateLabel } from './releaseConfirmCopy';

export type ReleaseSetsOperationKey = 'goodKit' | 'goodUnKit';

const RELEASE_DOC_MODE_BY_OPERATION: Record<ReleaseSetsOperationKey, string> = {
  goodKit: '1004000000000305',
  goodUnKit: '1004000000000306',
};

function preserveBatchBarcodes(
  nextBatches: ReleaseComponentBatch[],
  previousAllocations: ReleaseComponentAllocation[],
  sku: string,
): ReleaseComponentBatch[] {
  const previousByBatchId = new Map<string, string>();
  for (const batch of previousAllocations.find((allocation) => allocation.sku === sku)?.batches ?? []) {
    const barcode = String(batch.barcode ?? '').trim();
    if (barcode) {
      previousByBatchId.set(batch.batchId, barcode);
    }
  }

  return nextBatches.map((batch) => {
    const barcode = String(batch.barcode ?? '').trim() || previousByBatchId.get(batch.batchId);
    return barcode ? { ...batch, barcode } : batch;
  });
}

function sortBatchesByStockDesc(batches: ReleaseComponentBatch[]): ReleaseComponentBatch[] {
  return [...batches].sort((left, right) => {
    const leftQty = Number(left.batchStock ?? left.quantity ?? 0);
    const rightQty = Number(right.batchStock ?? right.quantity ?? 0);
    return rightQty - leftQty;
  });
}

/** Автопідстановка (крок 2): без системних Dilovod-партій; у picker вони лишаються для ручного вибору. */
function filterAutoGeneratedReleaseBatches(
  allocations: ReleaseComponentAllocation[],
): ReleaseComponentAllocation[] {
  return allocations
    .map((allocation) => ({
      ...allocation,
      batches: (allocation.batches ?? []).filter((batch) => {
        const label = String(batch.batchNumber ?? batch.batchId ?? '').trim();
        return !isAutoGeneratedSystemBatch(label);
      }),
    }))
    .filter((allocation) => allocation.batches.length > 0);
}

function resolveSourceSkuFromSetItem(item: ReleaseSetItem | null | undefined): string | null {
  const direct = String(item?.sourceSku ?? '').trim();
  if (direct) return direct;

  const snapshot = item?.componentsSnapshot;
  if (!Array.isArray(snapshot) || snapshot.length === 0) return null;

  const first = snapshot[0];
  return String(first?.id ?? first?.sku ?? first?.code ?? '').trim() || null;
}

function buildFillBatchesAllocation(
  sku: string,
  result: FillBatchesResult,
  previousAllocations: ReleaseComponentAllocation[],
): ReleaseComponentAllocation[] {
  const batches = sortBatchesByStockDesc(
    preserveBatchBarcodes(
      dedupePositiveStockBatches(result.batches).map((batch) => {
        const batchStock = Number(batch.quantity ?? 0);
        return {
          ...batch,
          batchStock,
          quantity: batchStock,
        };
      }),
      previousAllocations,
      sku,
    ),
  );

  if (batches.length === 0) return [];
  return [{ sku, batches }];
}

function dedupePositiveStockBatches(batches: ReleaseComponentBatch[]): ReleaseComponentBatch[] {
  const seen = new Set<string>();
  const result: ReleaseComponentBatch[] = [];

  for (const batch of batches) {
    const batchId = String(batch.batchId ?? '').trim();
    const quantity = Number(batch.quantity ?? 0);
    if (!batchId || seen.has(batchId) || !Number.isFinite(quantity) || quantity <= 0) continue;
    seen.add(batchId);
    result.push({ ...batch, quantity });
  }

  return result;
}

export interface ReleaseSetItem {
  id: string;
  setSku: string;
  name: string;
  quantity: number;
  componentsSnapshot: any[];
  availableQuantity: number | null;
  sourceSku?: string | null;
  isCorrectionSet?: boolean;
}

export interface ReleaseHistoryPagination {
  page: number;
  limit: number;
  total: number;
  pages: number;
}

const DEFAULT_PAGINATION: ReleaseHistoryPagination = {
  page: 1,
  limit: 10,
  total: 0,
  pages: 1,
};

function getBomPerSetQuantity(componentsSnapshot: unknown, sku: string): number {
  if (!Array.isArray(componentsSnapshot)) return 1;

  for (const component of componentsSnapshot) {
    const componentSku = String(component?.id ?? component?.sku ?? component?.code ?? '').trim();
    if (componentSku !== sku) continue;
    const quantity = Number(component?.quantity ?? component?.qty ?? NaN);
    if (Number.isFinite(quantity) && quantity > 0) return quantity;
  }

  return 1;
}

function getBatchStockLimit(batch: ReleaseComponentBatch): number {
  if (typeof batch.batchStock === 'number' && Number.isFinite(batch.batchStock) && batch.batchStock >= 0) {
    return batch.batchStock;
  }

  return Number.POSITIVE_INFINITY;
}

function deriveSetQuantityFromComponentBatches(
  componentBatches: ReleaseComponentAllocation[],
  componentsSnapshot: unknown,
): number | null {
  const candidates: number[] = [];

  for (const allocation of componentBatches) {
    const allocated = (allocation.batches ?? []).reduce(
      (sum, batch) => sum + Number(batch.quantity ?? 0),
      0,
    );
    if (allocated <= 0) continue;

    const perSet = getBomPerSetQuantity(componentsSnapshot, allocation.sku);
    if (perSet <= 0) continue;

    candidates.push(allocated / perSet);
  }

  if (candidates.length === 0) return null;

  const derived = Math.min(...candidates);
  if (!Number.isFinite(derived) || derived <= 0) return null;

  return derived;
}

function syncComponentBatchesForSetQuantity(
  componentBatches: ReleaseComponentAllocation[],
  componentsSnapshot: unknown,
  newSetQuantity: number,
  oldSetQuantity?: number | null,
): ReleaseComponentAllocation[] {
  if (newSetQuantity <= 0 || componentBatches.length === 0) {
    return componentBatches;
  }

  const scaleFactor = oldSetQuantity && oldSetQuantity > 0
    ? newSetQuantity / oldSetQuantity
    : null;

  return componentBatches.map((allocation) => {
    const perSet = getBomPerSetQuantity(componentsSnapshot, allocation.sku);
    const newRequired = perSet * newSetQuantity;
    const batches = [...(allocation.batches ?? [])];
    if (batches.length === 0) return allocation;

    const oldAllocated = batches.reduce((sum, batch) => sum + Number(batch.quantity ?? 0), 0);
    if (newRequired <= 0) {
      return { ...allocation, batches: [] };
    }

    const scaled = batches.map((batch) => {
      const batchStock = getBatchStockLimit(batch);
      const raw = scaleFactor !== null
        ? Number(batch.quantity ?? 0) * scaleFactor
        : oldAllocated > 0
          ? (Number(batch.quantity ?? 0) * newRequired) / oldAllocated
          : 0;
      return {
        ...batch,
        quantity: Math.min(batchStock, Math.max(0, Math.round(raw))),
      };
    });

    let diff = newRequired - scaled.reduce((sum, batch) => sum + batch.quantity, 0);
    if (diff !== 0) {
      const adjustable = scaled
        .map((batch, index) => ({ batch, index }))
        .sort((left, right) => {
          const leftRoom = getBatchStockLimit(left.batch) - left.batch.quantity;
          const rightRoom = getBatchStockLimit(right.batch) - right.batch.quantity;
          return diff > 0 ? rightRoom - leftRoom : left.batch.quantity - right.batch.quantity;
        });

      for (const { index } of adjustable) {
        if (diff === 0) break;
        const batch = scaled[index];
        const stock = getBatchStockLimit(batch);
        if (diff > 0) {
          const add = Math.min(diff, stock - batch.quantity);
          if (add <= 0) continue;
          scaled[index] = { ...batch, quantity: batch.quantity + add };
          diff -= add;
        } else {
          const remove = Math.min(-diff, batch.quantity);
          if (remove <= 0) continue;
          scaled[index] = { ...batch, quantity: batch.quantity - remove };
          diff += remove;
        }
      }
    }

    return {
      ...allocation,
      batches: scaled.filter((batch) => batch.quantity > 0),
    };
  });
}

function buildSingleBatchAllocation(
  sku: string,
  batch: { batchId: string; batchNumber: string; quantity: number },
  componentsSnapshot: unknown,
  setQuantity: number,
): ReleaseComponentAllocation | null {
  const batchStock = Math.max(0, Number(batch.quantity ?? 0));
  if (!batch.batchId || batchStock <= 0) return null;

  const perSet = getBomPerSetQuantity(componentsSnapshot, sku);
  const required = perSet * setQuantity;

  return {
    sku,
    batches: [{
      batchId: batch.batchId,
      batchNumber: batch.batchNumber,
      quantity: Math.min(batchStock, required),
      batchStock,
    }],
  };
}

async function fetchComponentBatchesBySku(
  skus: string[],
  options: {
    storageId?: string | null;
    firmId?: string | null;
    asOfDate?: string | null;
  },
): Promise<Record<string, Array<{ batchId: string; batchNumber: string; quantity: number }>>> {
  if (skus.length === 0) return {};

  const url = new URL('/api/warehouse/batch-numbers', window.location.origin);
  url.searchParams.set('skus', skus.join(','));
  if (options.firmId) url.searchParams.set('firmId', String(options.firmId));
  if (options.storageId) url.searchParams.set('storageId', String(options.storageId));
  if (options.asOfDate) url.searchParams.set('asOfDate', options.asOfDate);

  const response = await fetch(url.toString(), { credentials: 'include' });
  if (!response.ok) return {};

  const json = await response.json().catch(() => null) as {
    success?: boolean;
    batchesBySku?: Record<string, Array<{ batchId: string; batchNumber: string; quantity: number }>>;
  } | null;

  if (!json?.success || !json.batchesBySku) return {};
  return json.batchesBySku;
}

function buildSingleBatchPrefillAllocations(
  setItem: ReleaseSetItem,
  batchesBySku: Record<string, Array<{ batchId: string; batchNumber: string; quantity: number }>>,
): ReleaseComponentAllocation[] {
  const components = Array.isArray(setItem.componentsSnapshot) ? setItem.componentsSnapshot : [];
  const setQuantity = Number(setItem.quantity ?? 1);
  const allocations: ReleaseComponentAllocation[] = [];

  for (const component of components) {
    const sku = String(component?.id ?? component?.sku ?? component?.code ?? '').trim();
    if (!sku) continue;

    const selectable = (batchesBySku[sku] ?? []).filter((batch) => {
      const label = String(batch.batchNumber ?? batch.batchId ?? '').trim();
      return !isAutoGeneratedSystemBatch(label) && Number(batch.quantity ?? 0) > 0;
    });

    if (selectable.length !== 1) continue;

    const allocation = buildSingleBatchAllocation(
      sku,
      selectable[0],
      setItem.componentsSnapshot,
      setQuantity,
    );
    if (allocation) allocations.push(allocation);
  }

  return allocations;
}

export default function useReleaseSets() {
  const returns = useWarehouseReturns();
  const { storages, selectedStorage, setSelectedStorage, selectedStorageName, defaultSmallStorageId } = useWarehouseParams({ returns });
  const [items, setItems] = useState<ReleaseSetItem[]>([]);
  const [operationKey, setOperationKey] = useState<ReleaseSetsOperationKey>('goodKit');
  const [componentBatches, setComponentBatches] = useState<ReleaseComponentAllocation[]>([]);
  const [previewComponents, setPreviewComponents] = useState<ReleasePreviewComponent[]>([]);
  const [correctionMode, setCorrectionMode] = useState(false);
  const [correctionSessionId, setCorrectionSessionId] = useState<string | null>(null);
  const [correctionSourceSku, setCorrectionSourceSku] = useState<string | null>(null);
  const [correctionSourceGoodId, setCorrectionSourceGoodId] = useState<string | null>(null);
  const [lastKitPrefillInfo, setLastKitPrefillInfo] = useState<{ releaseId: number | null; dilovodDocId: string | null } | null>(null);
  const [suggestedOperDate, setSuggestedOperDate] = useState<string | null>(null);
  const lastPrefilledSetSkuRef = useRef<string | null>(null);

  const [history, setHistory] = useState<any[]>([]);
  const [historyLoading, setHistoryLoading] = useState(false);
  const [historyPagination, setHistoryPagination] = useState<ReleaseHistoryPagination>(DEFAULT_PAGINATION);
  const [archiveSessions, setArchiveSessions] = useState<any[]>([]);
  const [archiveLoading, setArchiveLoading] = useState(false);
  const [archivePagination, setArchivePagination] = useState<ReleaseHistoryPagination>(DEFAULT_PAGINATION);
  const syncedSetQuantityRef = useRef<number | null>(null);

  const formatLocalDate = (date: Date): string => {
    const pad = (value: number): string => String(value).padStart(2, '0');
    return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`;
  };

  const parseLocalDate = (value: unknown): Date | null => {
    if (typeof value !== 'string' || value.trim() === '') {
      return null;
    }

    const trimmed = value.trim();
    const localMatch = /^(\d{4})-(\d{2})-(\d{2})[ T](\d{2}):(\d{2})(?::(\d{2}))?$/.exec(trimmed);
    if (localMatch) {
      const [, year, month, day, hours, minutes, seconds] = localMatch;
      return new Date(
        Number(year),
        Number(month) - 1,
        Number(day),
        Number(hours),
        Number(minutes),
        Number(seconds ?? '0'),
      );
    }

    const parsed = new Date(trimmed);
    return Number.isNaN(parsed.getTime()) ? null : parsed;
  };

  const getPayloadDate = (): string | null => {
    const parsed = parseLocalDate(returns.returnDate);
    return parsed ? formatLocalDate(parsed) : null;
  };

  const isDeletedRelease = (record: any): boolean => String(record?.status ?? '').toLowerCase() === 'deleted';

  useEffect(() => {
    returns.loadAvailableFirms?.().catch(() => { /* ignore */ });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const refreshPreviewComponents = useCallback(async () => {
    if (items.length === 0) {
      setPreviewComponents([]);
      return;
    }

    try {
      const body = {
        items: items.map((item) => ({
          set_sku: item.setSku,
          quantity: item.quantity,
          components_snapshot: item.componentsSnapshot,
        })),
        componentBatches,
        correctionSessionId: correctionMode ? correctionSessionId : undefined,
      };
      const resp = await fetch('/api/warehouse/releases/preview', {
        method: 'POST',
        credentials: 'include',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });
      const json = await resp.json().catch(() => ({}));
      if (resp.ok && json.success && Array.isArray(json.data)) {
        setPreviewComponents(json.data);
      }
    } catch {
      // ignore preview errors in UI
    }
  }, [items, componentBatches, correctionMode, correctionSessionId]);

  useEffect(() => {
    const timer = setTimeout(() => {
      void refreshPreviewComponents();
    }, 200);
    return () => clearTimeout(timer);
  }, [refreshPreviewComponents]);

  const itemsSkuSignature = useMemo(
    () => items.map((item) => item.setSku).sort().join('|'),
    [items],
  );

  useEffect(() => {
    const storageId = selectedStorage ?? defaultSmallStorageId ?? null;
    if (!storageId || items.length === 0) return;

    const skus = items.map((item) => item.setSku).filter(Boolean);
    if (skus.length === 0) return;

    let cancelled = false;
    const timer = setTimeout(async () => {
      try {
        const response = await fetch('/api/warehouse/stock-snapshot', {
          method: 'POST',
          credentials: 'include',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            skus,
            storageId,
            firmId: returns.receiveFirmId ?? undefined,
          }),
        });
        if (!response.ok || cancelled) return;

        const json = await response.json().catch(() => null);
        if (!json?.success || typeof json.stocks !== 'object' || json.stocks == null) return;

        setItems((prev) => prev.map((item) => {
          const stock = json.stocks[item.setSku];
          const qty = Number(stock?.selectedStock ?? 0);
          const itemQty = Number(item.quantity ?? 0);
          const availableQuantity = Number.isFinite(qty) && qty > 0
            ? qty
            : (item.isCorrectionSet && Number.isFinite(itemQty) && itemQty > 0 ? itemQty : null);
          return {
            ...item,
            availableQuantity,
          };
        }));
      } catch {
        // ignore transient stock refresh errors
      }
    }, 200);

    return () => {
      cancelled = true;
      clearTimeout(timer);
    };
  }, [itemsSkuSignature, selectedStorage, defaultSmallStorageId, returns.receiveFirmId, items.length]);

  const addSet = async (setItem: any) => {
    if (items.length > 0) {
      return;
    }

    const availableQuantity = Number(setItem.availableQuantity ?? setItem.stockQuantity ?? setItem.stock ?? 0);
    const isCorrectionUnkit = correctionMode && operationKey === 'goodUnKit';
    const resolvedAvailable = Number.isFinite(availableQuantity) && availableQuantity > 0 ? availableQuantity : null;
    const defaultQuantity = isCorrectionUnkit && resolvedAvailable != null
      ? resolvedAvailable
      : (setItem.quantity ?? 1);
    const id = crypto.randomUUID?.() ?? `${setItem.sku}-${Date.now()}`;
    const newItem: ReleaseSetItem = {
      id,
      setSku: setItem.sku,
      name: setItem.name || setItem.title || setItem.sku,
      quantity: defaultQuantity,
      componentsSnapshot: setItem.componentsSnapshot ?? setItem.set ?? [],
      availableQuantity: resolvedAvailable,
      sourceSku: setItem.sourceSku ?? null,
      isCorrectionSet: Boolean(setItem.isCorrectionSet),
    };
    setItems([newItem]);
    setComponentBatches([]);
    syncedSetQuantityRef.current = Number(newItem.quantity ?? 1);
    setLastKitPrefillInfo(null);
    setSuggestedOperDate(null);
    lastPrefilledSetSkuRef.current = null;

    if (!correctionMode && operationKey === 'goodKit') {
      const componentSkus = (Array.isArray(newItem.componentsSnapshot) ? newItem.componentsSnapshot : [])
        .map((component) => String(component?.id ?? component?.sku ?? component?.code ?? '').trim())
        .filter(Boolean);

      if (componentSkus.length > 0) {
        try {
          const batchesBySku = await fetchComponentBatchesBySku(componentSkus, {
            storageId: selectedStorage ?? defaultSmallStorageId ?? null,
            firmId: returns.receiveFirmId ?? null,
            asOfDate: getPayloadDate(),
          });
          const allocations = buildSingleBatchPrefillAllocations(newItem, batchesBySku);
          if (allocations.length > 0) {
            setComponentBatches(allocations);
          }
        } catch {
          // автопідстановка опційна
        }
      }
    }
  };

  const buildSetRemark = (item: ReleaseSetItem | null): string | null => {
    if (!item) return null;

    const quantity = Number(item.quantity ?? 0);
    const safeQuantity = Number.isFinite(quantity) && quantity > 0 ? quantity : 1;
    const setName = String(item.name || item.setSku || '').trim();
    if (!setName) return null;

    if (correctionMode) {
      return `Корегування парт. обліку – ${setName} (${safeQuantity} шт.)`;
    }

    return `${safeQuantity} х ${setName}`;
  };

  const updateItem = (id: string, patch: Partial<ReleaseSetItem>) => {
    setItems((prev) => {
      const target = prev.find((item) => item.id === id);
      if (!target) return prev;

      const nextItems = prev.map((item) => (item.id === id ? { ...item, ...patch } : item));

      if (patch.quantity !== undefined) {
        const newQuantity = Number(patch.quantity);
        const prevQuantity = syncedSetQuantityRef.current ?? Number(target.quantity ?? 1);
        const shouldSyncBatches = newQuantity > 0
          && prevQuantity > 0
          && Math.abs(newQuantity - prevQuantity) > 0.0001
          && !(correctionMode && operationKey === 'goodKit');

        if (shouldSyncBatches) {
          syncedSetQuantityRef.current = newQuantity;
          setComponentBatches((batches) => {
            if (batches.length === 0) return batches;
            return syncComponentBatchesForSetQuantity(
              batches,
              target.componentsSnapshot,
              newQuantity,
              prevQuantity,
            );
          });
        } else if (Number.isFinite(newQuantity) && newQuantity > 0) {
          syncedSetQuantityRef.current = newQuantity;
        }
      }

      return nextItems;
    });
  };

  const removeItem = (id: string) => {
    setItems((prev) => prev.filter((item) => item.id !== id));
    setComponentBatches([]);
    syncedSetQuantityRef.current = null;
    setLastKitPrefillInfo(null);
    lastPrefilledSetSkuRef.current = null;
  };

  const clearAll = () => {
    returns.resetAllState?.();
    setItems([]);
    setComponentBatches([]);
    syncedSetQuantityRef.current = null;
    setPreviewComponents([]);
    setCorrectionSourceSku(null);
    setCorrectionSourceGoodId(null);
    setLastKitPrefillInfo(null);
    setSuggestedOperDate(null);
    lastPrefilledSetSkuRef.current = null;
  };

  const resetCorrectionState = () => {
    clearAll();
    setCorrectionMode(false);
    setCorrectionSessionId(null);
    setCorrectionSourceSku(null);
    setCorrectionSourceGoodId(null);
  };

  const ensureCorrectionSet = async (sourceSku: string): Promise<EnsureInventorySetResult> => {
    const resp = await fetch('/api/warehouse/releases/batch-correction/ensure-set', {
      method: 'POST',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ sourceSku }),
    });
    const json = await resp.json().catch(() => ({}));
    if (!resp.ok || !json.success) {
      throw new Error(json.error || 'Не вдалося створити інвентаризаційний набір');
    }
    return json.data as EnsureInventorySetResult;
  };

  const fillAllBatches = async (sku: string, asOfDate?: string | null): Promise<FillBatchesResult> => {
    const resp = await fetch('/api/warehouse/releases/batch-correction/fill-batches', {
      method: 'POST',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        sku,
        storageId: selectedStorage ?? defaultSmallStorageId,
        firmId: returns.receiveFirmId,
        asOfDate: asOfDate ?? getPayloadDate(),
      }),
    });
    const json = await resp.json().catch(() => ({}));
    if (!resp.ok || !json.success) {
      throw new Error(json.error || 'Не вдалося підставити партії');
    }
    return json.data as FillBatchesResult;
  };

  const applyFillBatches = async (sku: string) => {
    const result = await fillAllBatches(sku);
    const allocations = buildFillBatchesAllocation(sku, result, componentBatches);
    if (allocations.length === 0) {
      throw new Error('На складі немає партій з позитивним залишком');
    }
    setComponentBatches(allocations);
    const batches = allocations[0]?.batches ?? [];
    return { ...result, batches, batchCount: batches.length, totalQuantity: batches.reduce((sum, batch) => sum + batch.quantity, 0) };
  };

  const fetchSetStockQuantity = async (setSku: string, asOfDate?: string | null): Promise<number | null> => {
    const storageId = selectedStorage ?? defaultSmallStorageId ?? null;
    if (!setSku || !storageId) return null;

    try {
      const response = await fetch('/api/warehouse/stock-snapshot', {
        method: 'POST',
        credentials: 'include',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          skus: [setSku],
          storageId,
          firmId: returns.receiveFirmId ?? undefined,
          asOfDate: asOfDate ?? undefined,
        }),
      });
      if (!response.ok) return null;

      const json = await response.json().catch(() => null);
      const stock = json?.stocks?.[setSku];
      const qty = Number(stock?.selectedStock ?? 0);
      return Number.isFinite(qty) && qty > 0 ? qty : null;
    } catch {
      return null;
    }
  };

  const loadLastKitBatches = async (
    setSku: string,
    currentItem?: ReleaseSetItem | null,
  ): Promise<ReleaseLastKitBatchesResponse & { shiftedDate?: string | null }> => {
    const url = new URL('/api/warehouse/releases/last-kit-batches', window.location.origin);
    url.searchParams.set('setSku', setSku);
    if (selectedStorage) url.searchParams.set('storageId', selectedStorage);
    if (returns.receiveFirmId) url.searchParams.set('firmId', String(returns.receiveFirmId));

    const resp = await fetch(url.toString(), { credentials: 'include' });
    const json = await resp.json().catch(() => ({}));
    if (!resp.ok || !json.success) {
      throw new Error(json.error || 'Не вдалося завантажити партії останнього комплектування');
    }

    const data = (json.data ?? {}) as ReleaseLastKitBatchesResponse;
    setLastKitPrefillInfo({
      releaseId: data.releaseId ?? null,
      dilovodDocId: data.dilovodDocId ?? null,
    });

    let shiftedDate: string | null = null;
    const existingDate = parseLocalDate(returns.returnDate);
    const kitDate = parseLocalDate(data.operDate);
    if (kitDate && !existingDate) {
      kitDate.setMinutes(kitDate.getMinutes() + 1);
      shiftedDate = formatLocalDate(kitDate);
      returns.setReturnDate?.(shiftedDate);
      setSuggestedOperDate(shiftedDate);
    }

    const activeItem = currentItem ?? items[0] ?? null;
    const payloadDate = shiftedDate ?? getPayloadDate();
    const maxSetQuantity = correctionMode && operationKey === 'goodUnKit'
      ? await fetchSetStockQuantity(setSku, payloadDate)
      : null;

    if (maxSetQuantity != null) {
      const currentQuantity = Number(activeItem?.quantity ?? 1);
      if (!Number.isFinite(currentQuantity) || currentQuantity < maxSetQuantity) {
        syncedSetQuantityRef.current = maxSetQuantity;
        setItems((prev) => prev.map((item) => (
          item.setSku === setSku
            ? { ...item, quantity: maxSetQuantity, availableQuantity: maxSetQuantity }
            : item
        )));
      }
    }

    let allocations = filterAutoGeneratedReleaseBatches(
      Array.isArray(data.componentBatches) ? data.componentBatches : [],
    );

    const sourceSku = resolveSourceSkuFromSetItem(activeItem);
    if (allocations.length === 0 && sourceSku) {
      try {
        const fillResult = await fillAllBatches(sourceSku, payloadDate);
        allocations = filterAutoGeneratedReleaseBatches(
          buildFillBatchesAllocation(sourceSku, fillResult, componentBatches),
        );
      } catch {
        // fallback is optional
      }
    }

    if (allocations.length > 0) {
      const setQuantity = maxSetQuantity
        ?? Number(activeItem?.quantity ?? syncedSetQuantityRef.current ?? 1);
      const safeQuantity = Number.isFinite(setQuantity) && setQuantity > 0 ? setQuantity : 1;
      const scaled = syncComponentBatchesForSetQuantity(
        allocations,
        activeItem?.componentsSnapshot,
        safeQuantity,
      );
      setComponentBatches(scaled);
      syncedSetQuantityRef.current = safeQuantity;
    }

    return { ...data, shiftedDate };
  };

  const transitionToCorrectionUnkitStep = (snapshot: ReleaseSetItem, baseDate?: string | null): string | null => {
    const quantity = Number(snapshot.quantity ?? 1);
    const safeQuantity = Number.isFinite(quantity) && quantity > 0 ? quantity : 1;
    const id = snapshot.id || crypto.randomUUID?.() || `${snapshot.setSku}-${Date.now()}`;

    const newItem: ReleaseSetItem = {
      ...snapshot,
      id,
      quantity: safeQuantity,
      availableQuantity: safeQuantity,
      isCorrectionSet: true,
    };

    // +1 хв відносно комплектування — залишки на момент після kit, не до нього
    let shiftedDate: string | null = null;
    const parsed = parseLocalDate(baseDate ?? returns.returnDate);
    if (parsed) {
      parsed.setMinutes(parsed.getMinutes() + 1);
      shiftedDate = formatLocalDate(parsed);
      returns.setReturnDate?.(shiftedDate);
    }

    setOperationKey('goodUnKit');
    setItems([newItem]);
    setComponentBatches([]);
    syncedSetQuantityRef.current = safeQuantity;
    setLastKitPrefillInfo(null);
    lastPrefilledSetSkuRef.current = null;
    return shiftedDate;
  };

  const selectCorrectionProduct = async (product: any) => {
    const sourceSku = String(product.sku ?? '').trim();
    if (!sourceSku || isRebatchSku(sourceSku)) {
      throw new Error('Некоректний товар для коригування');
    }

    const ensured = await ensureCorrectionSet(sourceSku);
    const productResp = await fetch(`/api/products/batch?skus=${encodeURIComponent(ensured.setSku)}&fields=name,set`, {
      credentials: 'include',
    });
    const productJson = await productResp.json().catch(() => ({}));
    const ensuredProduct = Array.isArray(productJson?.products) ? productJson.products[0] : null;
    const componentsSnapshot = Array.isArray(ensuredProduct?.set) ? ensuredProduct.set : [{ id: sourceSku, sku: sourceSku, quantity: 1, name: product.name }];

    const sessionId = correctionSessionId ?? crypto.randomUUID?.() ?? `corr-${Date.now()}`;
    if (!correctionSessionId) {
      setCorrectionSessionId(sessionId);
    }
    setCorrectionSourceSku(sourceSku);
    setCorrectionSourceGoodId(String(product.dilovodId ?? product.id ?? '').trim() || null);

    await addSet({
      sku: ensured.setSku,
      name: ensured.setName,
      quantity: 1,
      componentsSnapshot,
      sourceSku,
      isCorrectionSet: true,
    });
  };

  const buildSendBody = (dryRun: boolean) => {
    const currentItems = items.map((item) => ({
      set_sku: item.setSku,
      quantity: item.quantity,
      components_snapshot: item.componentsSnapshot,
    }));

    return {
      items: currentItems,
      setSku: items[0]?.setSku,
      quantity: items[0]?.quantity,
      storageId: selectedStorage,
      date: getPayloadDate(),
      firmId: returns.receiveFirmId ?? undefined,
      comment: returns.comment ?? null,
      remark: buildSetRemark(items[0] ?? null),
      docMode: RELEASE_DOC_MODE_BY_OPERATION[operationKey],
      operationType: operationKey === 'goodUnKit' ? 'unkit' : 'kit',
      componentBatches,
      dryRun,
      requireBatches: componentBatches.length > 0,
      correctionSessionId,
    };
  };

  const buildPreview = async () => {
    const body = buildSendBody(true);
    const resp = await fetch('/api/warehouse/releases/send', {
      method: 'POST',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    return resp.ok ? await resp.json().catch(() => null) : null;
  };

  const previewKitOutputBatch = useCallback(async (): Promise<KitOutputBatchInfo | null> => {
    if (correctionMode || operationKey !== 'goodKit' || items.length === 0) {
      return null;
    }

    const setSku = String(items[0]?.setSku ?? '').trim();
    if (!setSku || isRebatchSku(setSku)) {
      return null;
    }

    const resp = await fetch('/api/warehouse/releases/kit-output-batch/preview', {
      method: 'POST',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        setSku,
        date: getPayloadDate(),
        componentBatches,
        correctionSessionId,
      }),
    });
    const json = await resp.json().catch(() => ({}));
    if (!resp.ok || !json?.success) {
      return null;
    }
    return (json.data as KitOutputBatchInfo | null) ?? null;
  }, [
    correctionMode,
    operationKey,
    items,
    componentBatches,
    correctionSessionId,
    getPayloadDate,
  ]);

  const requestSend = async (options?: {
    createSurplusBatch?: boolean;
    surplusQuantity?: number;
    surplusGoodId?: string | null;
  }) => {
    const currentItems = items.map((item) => ({
      set_sku: item.setSku,
      quantity: item.quantity,
      components_snapshot: item.componentsSnapshot,
    }));
    const currentRemark = buildSetRemark(items[0] ?? null);

    const body = {
      ...buildSendBody(false),
      status: 'created',
      createSurplusBatch: options?.createSurplusBatch === true,
      surplusQuantity: options?.surplusQuantity,
      surplusGoodId: options?.surplusGoodId ?? undefined,
    };

    const resp = await fetch('/api/warehouse/releases/send', {
      method: 'POST',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    const json = await resp.json().catch(() => ({}));

    if (resp.ok && json.success) {
      let historySaved = json.historySaved === true;
      let historyResponse: Record<string, unknown> | null = null;

      if (!historySaved) {
        const historyComment = [currentRemark, returns.comment ? String(returns.comment).trim() : ''].filter(Boolean).join(' | ') || null;
        const operationDate = getPayloadDate();
        const historyItems = currentItems.map((item) => ({
          ...item,
          operationDate,
        }));

        const historyResp = await fetch('/api/warehouse/releases', {
          method: 'POST',
          credentials: 'include',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            items: historyItems,
            storageId: selectedStorage,
            firmId: returns.receiveFirmId ?? undefined,
            comment: historyComment,
            remark: currentRemark,
            status: 'created',
            operationType: operationKey === 'goodUnKit' ? 'unkit' : 'kit',
            operDate: operationDate,
            dilovodDocId: json.dilovodDocId ?? null,
            componentBatches,
            correctionSessionId,
          }),
        });
        historyResponse = await historyResp.json().catch(() => ({}));
        historySaved = Boolean(historyResp.ok && historyResponse?.success);
      }

      setItems([]);
      setComponentBatches([]);
      setPreviewComponents([]);
      setLastKitPrefillInfo(null);

      if (historySaved) {
        await loadHistory(historyPagination.page, historyPagination.limit);
      }

      return {
        ...json,
        historySaved,
        historyResponse,
      };
    }

    return json;
  };

  const fetchReleases = async (status: 'active' | 'deleted', page: number, limit: number) => {
    const url = new URL('/api/warehouse/releases', window.location.origin);
    url.searchParams.set('status', status);
    url.searchParams.set('page', String(page));
    url.searchParams.set('limit', String(limit));
    const resp = await fetch(url.toString(), { credentials: 'include' });
    const json = await resp.json().catch(() => ({}));
    if (!resp.ok || !json.success) {
      throw new Error(json.error || 'Не вдалося завантажити історію');
    }
    return {
      records: Array.isArray(json.data) ? json.data : [],
      pagination: json.pagination ?? { ...DEFAULT_PAGINATION, page, limit },
    };
  };

  const loadHistory = async (page = historyPagination.page, limit = historyPagination.limit) => {
    setHistoryLoading(true);
    try {
      const result = await fetchReleases('active', page, limit);
      setHistory(result.records.filter((record: any) => !isDeletedRelease(record)));
      setHistoryPagination(result.pagination);
    } catch {
      // ignore
    } finally {
      setHistoryLoading(false);
    }
  };

  const loadArchive = async (page = archivePagination.page, limit = archivePagination.limit) => {
    setArchiveLoading(true);
    try {
      const result = await fetchReleases('deleted', page, limit);
      setArchiveSessions(result.records.filter((record: any) => isDeletedRelease(record)));
      setArchivePagination(result.pagination);
    } catch {
      // ignore
    } finally {
      setArchiveLoading(false);
    }
  };

  const deleteRecord = async (id: number, forceLocal = false) => {
    const url = forceLocal
      ? `/api/warehouse/releases/${encodeURIComponent(String(id))}?forceLocal=true`
      : `/api/warehouse/releases/${encodeURIComponent(String(id))}`;
    const resp = await fetch(url, { method: 'DELETE', credentials: 'include' });
    const json = await resp.json().catch(() => ({}));
    return { ok: resp.ok, status: resp.status, json };
  };

  const correctionStep = useMemo(() => {
    if (!correctionMode) return null;
    return operationKey === 'goodKit' ? 1 : 2;
  }, [correctionMode, operationKey]);

  const correctionUnkitDiff = useMemo(() => {
    const expected = previewComponents.reduce((sum, component) => sum + Number(component.quantity ?? 0), 0);
    const counted = componentBatches.reduce((sum, allocation) => {
      const batchSum = (allocation.batches ?? []).reduce((inner, batch) => inner + Number(batch.quantity ?? 0), 0);
      return sum + batchSum;
    }, 0);
    return {
      expected,
      counted,
      shortage: Math.max(0, expected - counted),
      surplus: Math.max(0, counted - expected),
      surplusBatchName: formatCorrectionBatchDateLabel(),
    };
  }, [previewComponents, componentBatches]);

  const areComponentBatchesComplete = useMemo(() => {
    if (previewComponents.length === 0) return false;

    const allocationBySku = new Map(
      componentBatches.map((allocation) => [allocation.sku, allocation.batches ?? []]),
    );

    return previewComponents.every((component) => {
      const required = Number(component.quantity ?? 0);
      if (required <= 0) return true;

      const batches = allocationBySku.get(component.sku) ?? [];
      if (batches.length === 0) return false;

      const allocated = batches.reduce((sum, batch) => sum + Number(batch.quantity ?? 0), 0);
      return Math.abs(allocated - required) < 0.0001;
    });
  }, [previewComponents, componentBatches]);

  const activeSetQuantity = items[0]?.quantity;
  const activeSetId = items[0]?.id;
  const activeComponentsSnapshot = items[0]?.componentsSnapshot;

  useEffect(() => {
    if (!correctionMode || operationKey !== 'goodKit' || !activeSetId) {
      return;
    }

    const hasPositiveAllocation = componentBatches.some((allocation) =>
      (allocation.batches ?? []).some((batch) => Number(batch.quantity ?? 0) > 0),
    );

    const nextQuantity = hasPositiveAllocation
      ? deriveSetQuantityFromComponentBatches(componentBatches, activeComponentsSnapshot)
      : 1;

    if (nextQuantity === null) {
      return;
    }

    const currentQuantity = Number(activeSetQuantity ?? 1);
    if (Math.abs(currentQuantity - nextQuantity) < 0.0001) {
      syncedSetQuantityRef.current = nextQuantity;
      return;
    }

    syncedSetQuantityRef.current = nextQuantity;
    setItems((prev) => {
      if (prev.length === 0) return prev;
      const item = prev[0];
      if (item.id !== activeSetId) return prev;
      return [{ ...item, quantity: nextQuantity }];
    });
  }, [
    correctionMode,
    operationKey,
    activeSetId,
    activeSetQuantity,
    activeComponentsSnapshot,
    componentBatches,
  ]);

  useEffect(() => {
    if (!activeSetId) {
      syncedSetQuantityRef.current = null;
      return;
    }

    const quantity = Number(activeSetQuantity ?? 1);
    if (!Number.isFinite(quantity) || quantity <= 0) {
      return;
    }

    if (correctionMode && operationKey === 'goodKit') {
      syncedSetQuantityRef.current = quantity;
      return;
    }

    if (componentBatches.length === 0) {
      syncedSetQuantityRef.current = quantity;
      return;
    }

    if (syncedSetQuantityRef.current === null) {
      syncedSetQuantityRef.current = quantity;
      return;
    }

    if (syncedSetQuantityRef.current === quantity) {
      return;
    }

    const prevQuantity = syncedSetQuantityRef.current ?? quantity;
    syncedSetQuantityRef.current = quantity;
    setComponentBatches((batches) => syncComponentBatchesForSetQuantity(
      batches,
      activeComponentsSnapshot,
      quantity,
      prevQuantity,
    ));
  }, [
    activeSetId,
    activeSetQuantity,
    activeComponentsSnapshot,
    componentBatches.length,
    correctionMode,
    operationKey,
  ]);

  useEffect(() => {
    void loadHistory();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!correctionMode || operationKey !== 'goodUnKit' || items.length === 0) return;
    const item = items[0];
    const setSku = item?.setSku;
    if (!setSku || lastPrefilledSetSkuRef.current === setSku) return;

    lastPrefilledSetSkuRef.current = setSku;
    void loadLastKitBatches(setSku, item).catch(() => {
      lastPrefilledSetSkuRef.current = null;
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [correctionMode, operationKey, items[0]?.setSku, selectedStorage, returns.receiveFirmId, defaultSmallStorageId]);

  return {
    returns,
    items,
    operationKey,
    setOperationKey,
    componentBatches,
    setComponentBatches,
    previewComponents,
    correctionMode,
    setCorrectionMode,
    correctionSessionId,
    correctionSourceSku,
    correctionSourceGoodId,
    correctionStep,
    correctionUnkitDiff,
    areComponentBatchesComplete,
    lastKitPrefillInfo,
    suggestedOperDate,
    addSet,
    buildSetRemark,
    updateItem,
    removeItem,
    clearAll,
    resetCorrectionState,
    ensureCorrectionSet,
    fillAllBatches,
    applyFillBatches,
    loadLastKitBatches,
    transitionToCorrectionUnkitStep,
    selectCorrectionProduct,
    buildRebatchSku,
    storages,
    selectedStorage,
    selectedStorageName,
    defaultSmallStorageId,
    setSelectedStorage,
    buildPreview,
    previewKitOutputBatch,
    requestSend,
    history,
    historyLoading,
    historyPagination,
    archiveSessions,
    archiveLoading,
    archivePagination,
    loadHistory,
    loadArchive,
    deleteRecord,
    getPayloadDate,
    parseLocalDate,
  };
}
