import { useEffect, useMemo, useRef, useState } from 'react';
import { canSetTpGoodsGoodPart, isAutoGeneratedSystemBatch } from '@shared/utils/dilovodBatchId';
import { allocateBatchesFifo } from '@shared/utils/fifoBatchAllocation';
import { Button, Card, Spinner } from '@heroui/react';
import { DynamicIcon } from 'lucide-react/dynamic';
import { StepperInput } from '../../shared/StepperInput';
import { QtyPills } from '../../shared/QtyPills';
import { ConfirmModal } from '@/components/modals/ConfirmModal';
import { BatchNumbersAutocomplete } from '../../WarehouseMovement/components/BatchNumbersAutocomplete';
import { useBatchNumbers, type BatchNumber } from '../../WarehouseMovement/hooks/useBatchNumbers';
import { ToastService } from '@/services/ToastService';
import { useProductMovementsDrawer } from '@/features/product-movements/context/ProductMovementsDrawerContext';
import type { ReleaseComponentAllocation, ReleaseComponentBatch } from '@shared/types/warehouseRelease';
import type { ReleaseSetsOperationKey } from '../useReleaseSets';
import { breakdownStockPortions } from '../../WarehouseMovementMob/WarehouseMovementMobUtils';

interface ComponentRow {
  sku: string;
  name: string | null;
  requiredQuantity: number;
  perSetQuantity?: number;
  portionsPerBox?: number | null;
}

interface Props {
  components: ComponentRow[];
  componentBatches: ReleaseComponentAllocation[];
  onChange: (next: ReleaseComponentAllocation[]) => void;
  selectedDateTime?: Date | null;
  firmId?: string | null;
  storageId?: string | null;
  storageName?: string | null;
  readOnly?: boolean;
  operationKey?: ReleaseSetsOperationKey;
  correctionMode?: boolean;
  correctionStep?: number | null;
  onFillAllBatches?: () => void;
}

function formatPortionQty(value: number): string {
  return String(Math.round(value));
}

function ReleaseBatchMovementsButton({
  sku,
  productName,
  batchId,
  batchLabel,
  storageId,
}: {
  sku: string;
  productName: string | null;
  batchId: string;
  batchLabel: string;
  storageId?: string | null;
}) {
  const { open } = useProductMovementsDrawer();
  return (
    <Button
      size="sm"
      variant="light"
      className="min-w-0 gap-1"
      startContent={<DynamicIcon name="arrow-left-right" size={14} />}
      onPress={() => open({
        sku,
        productName: productName ?? undefined,
        goodPartId: batchId,
        batchLabel,
        storageId: storageId ?? undefined,
        autoGenerate: true,
      })}
    >
      Рухи партії
    </Button>
  );
}

function getOtherAllocatedQuantity(batches: ReleaseComponentBatch[], excludeIndex: number): number {
  return batches.reduce((sum, batch, batchIndex) => {
    if (batchIndex === excludeIndex) return sum;
    return sum + Number(batch.quantity ?? 0);
  }, 0);
}

function getBatchStockLimit(
  batch: ReleaseComponentBatch,
  sourceBatches: BatchNumber[],
  allowNegativeStock = false,
): number {
  if (typeof batch.batchStock === 'number' && Number.isFinite(batch.batchStock)) {
    if (allowNegativeStock || batch.batchStock >= 0) {
      return batch.batchStock;
    }
  }

  const source = sourceBatches.find((item) => item.batchId === batch.batchId);
  const fromSource = Number(source?.quantity ?? NaN);
  if (Number.isFinite(fromSource) && (allowNegativeStock || fromSource >= 0)) {
    return fromSource;
  }

  return Number.POSITIVE_INFINITY;
}

/** Фактичний залишок по обліку (включно з мінусами) для відображення в рядку партії. */
function getAccountingBatchStock(
  batch: ReleaseComponentBatch,
  sourceBatches: BatchNumber[],
): number | null {
  if (typeof batch.batchStock === 'number' && Number.isFinite(batch.batchStock)) {
    return batch.batchStock;
  }
  const source = sourceBatches.find((item) => item.batchId === batch.batchId);
  const fromSource = Number(source?.quantity ?? NaN);
  return Number.isFinite(fromSource) ? fromSource : null;
}

function getSuggestedBatchQuantity(
  batchStock: number,
  requiredQuantity: number,
  otherAllocated: number,
  limitByStockOnly = false,
  allowNegativeStock = false,
): number {
  const remainingNeeded = Math.max(0, requiredQuantity - otherAllocated);
  if (remainingNeeded <= 0) return 0;

  if (limitByStockOnly) {
    if (allowNegativeStock && batchStock < 0) {
      return Math.min(remainingNeeded, Math.abs(batchStock));
    }
    return batchStock > 0 ? Math.min(batchStock, remainingNeeded) : 0;
  }

  if (batchStock <= 0 && !allowNegativeStock) return 0;
  if (allowNegativeStock && batchStock < 0) {
    return Math.min(remainingNeeded, Math.abs(batchStock));
  }
  return Math.min(batchStock, remainingNeeded);
}

function getBatchQuantityMax(
  batch: ReleaseComponentBatch,
  requiredQuantity: number,
  otherAllocated: number,
  sourceBatches: BatchNumber[],
  limitByStockOnly = false,
  allowUnlimitedQuantity = false,
): number {
  if (allowUnlimitedQuantity) {
    return Math.max(0, requiredQuantity - otherAllocated);
  }

  const batchStock = getBatchStockLimit(batch, sourceBatches, limitByStockOnly);
  if (limitByStockOnly) {
    return Number.isFinite(batchStock) ? Math.max(0, batchStock) : Number.POSITIVE_INFINITY;
  }

  const remainingNeeded = Math.max(0, requiredQuantity - otherAllocated);
  return Math.min(batchStock, remainingNeeded);
}

function getAllocationMap(allocations: ReleaseComponentAllocation[]): Map<string, ReleaseComponentBatch[]> {
  const map = new Map<string, ReleaseComponentBatch[]>();
  for (const allocation of allocations) {
    map.set(allocation.sku, allocation.batches ?? []);
  }
  return map;
}

function filterSelectableWarehouseBatches(
  batches: BatchNumber[],
  hideAutoGeneratedBatches: boolean,
  allowNonPositiveQty: boolean,
): BatchNumber[] {
  return batches.filter((batch) => {
    const label = String(batch.batchNumber ?? batch.batchId ?? '').trim();
    if (hideAutoGeneratedBatches && isAutoGeneratedSystemBatch(label)) return false;
    // Document-id з балансу (prodOrder тощо) Dilovod не приймає як tpGoods.goodPart.
    if (!canSetTpGoodsGoodPart({ batchId: batch.batchId, batchNumber: batch.batchNumber })) return false;
    if (!allowNonPositiveQty && Number(batch.quantity ?? 0) <= 0) return false;
    return true;
  });
}

function hasUnselectedWarehouseBatches(
  selected: ReleaseComponentBatch[],
  available: BatchNumber[],
): boolean {
  const selectedIds = new Set(selected.map((batch) => batch.batchId));
  return available.some((batch) => !selectedIds.has(batch.batchId));
}

/** Bulk-партії без enrichment expiration (FIFO сортує за номером; менше getObject у Dilovod). */
function buildReleaseBulkBatchNumbersUrl(
  skus: string[],
  options: {
    firmId?: string | null;
    storageId?: string | null;
    selectedDateTime?: Date | null;
    includeNonPositiveQty?: boolean;
  },
): URL {
  const url = new URL('/api/warehouse/batch-numbers', window.location.origin);
  url.searchParams.set('skus', skus.join(','));
  url.searchParams.set('skipExpiration', 'true');
  if (options.firmId) url.searchParams.set('firmId', options.firmId);
  if (options.storageId) url.searchParams.set('storageId', options.storageId);
  if (options.selectedDateTime) {
    url.searchParams.set('asOfDate', options.selectedDateTime.toISOString());
  }
  if (options.includeNonPositiveQty) {
    url.searchParams.set('includeNonPositiveQty', 'true');
  }
  return url;
}

async function fetchBarcodeForBatch(sku: string, batchId: string): Promise<string | null> {
  const url = new URL('/api/warehouse/barcode-for-batch', window.location.origin);
  url.searchParams.set('sku', sku);
  url.searchParams.set('batchId', batchId);

  try {
    const response = await fetch(url.toString(), { credentials: 'include' });
    if (!response.ok) return null;
    const data = await response.json().catch(() => null) as { success?: boolean; barcode?: string | null } | null;
    if (!data || data.success === false) return null;
    const barcode = String(data.barcode ?? '').trim();
    return barcode || null;
  } catch {
    return null;
  }
}

export default function ReleaseComponentBatchesPanel({
  components,
  componentBatches,
  onChange,
  selectedDateTime,
  firmId,
  storageId,
  storageName,
  readOnly = false,
  operationKey = 'goodKit',
  correctionMode = false,
  correctionStep = null,
  onFillAllBatches,
}: Props) {
  const { batches, loading, fetchBatches } = useBatchNumbers();
  const [activeSku, setActiveSku] = useState<string | null>(null);
  const [editingBatchIndex, setEditingBatchIndex] = useState<number | null>(null);
  const [deleteConfirm, setDeleteConfirm] = useState<{ sku: string; index: number; batchNumber: string } | null>(null);
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const [fifoLoading, setFifoLoading] = useState(false);
  const [warehouseBatchesBySku, setWarehouseBatchesBySku] = useState<Record<string, BatchNumber[]>>({});
  const inputRef = useRef<HTMLInputElement>(null);
  const barcodeFetchAttemptedRef = useRef<Set<string>>(new Set());
  const autoSelectBatchKeyRef = useRef<string | null>(null);

  const allocationMap = useMemo(() => getAllocationMap(componentBatches), [componentBatches]);
  const isCorrectionUnkitStep = correctionMode && correctionStep === 2;
  const limitByStockOnly = correctionMode && !isCorrectionUnkitStep;
  const allowNegativeBatches = isCorrectionUnkitStep;
  const hideAutoGeneratedBatches = operationKey === 'goodKit' && !correctionMode;

  const selectableBatches = useMemo(
    () => batches.filter((batch) => {
      if (!canSetTpGoodsGoodPart({ batchId: batch.batchId, batchNumber: batch.batchNumber })) {
        return false;
      }
      if (hideAutoGeneratedBatches && isAutoGeneratedSystemBatch(batch.batchNumber)) {
        return false;
      }
      return true;
    }),
    [batches, hideAutoGeneratedBatches],
  );

  const activePortionsPerBox = useMemo(() => {
    if (!activeSku) return null;
    const component = components.find((item) => item.sku === activeSku);
    if (!component?.portionsPerBox || component.portionsPerBox <= 0) return null;
    return component.portionsPerBox;
  }, [activeSku, components]);

  const componentSkusKey = useMemo(
    () => [...new Set(components.map((component) => component.sku.trim()).filter(Boolean))].sort().join(','),
    [components],
  );

  useEffect(() => {
    if (readOnly || !componentSkusKey) {
      setWarehouseBatchesBySku({});
      return;
    }

    let cancelled = false;
    void (async () => {
      try {
        // У correction (особливо unkit) тягнемо й мінусові залишки — для «По обліку» і автопідстановки.
        const url = buildReleaseBulkBatchNumbersUrl(componentSkusKey.split(','), {
          firmId,
          storageId,
          selectedDateTime,
          includeNonPositiveQty: allowNegativeBatches || correctionMode,
        });

        const response = await fetch(url.toString(), { credentials: 'include' });
        const json = await response.json().catch(() => null) as {
          success?: boolean;
          batchesBySku?: Record<string, BatchNumber[]>;
        } | null;

        if (cancelled || !response.ok || !json?.success || !json.batchesBySku) return;
        setWarehouseBatchesBySku(json.batchesBySku);
      } catch {
        if (!cancelled) setWarehouseBatchesBySku({});
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [
    allowNegativeBatches,
    componentSkusKey,
    correctionMode,
    firmId,
    readOnly,
    selectedDateTime,
    storageId,
  ]);

  // Підставляємо batchStock з балансу складу, якщо в алокації його ще немає (історія / last-kit).
  useEffect(() => {
    if (readOnly || Object.keys(warehouseBatchesBySku).length === 0 || componentBatches.length === 0) {
      return;
    }

    let anyChanged = false;
    const next = componentBatches.map((allocation) => {
      const warehouse = warehouseBatchesBySku[allocation.sku] ?? [];
      if (warehouse.length === 0) return allocation;
      const stockById = new Map(
        warehouse.map((batch) => [batch.batchId, Number(batch.quantity ?? NaN)] as const),
      );
      let allocationChanged = false;
      const batches = (allocation.batches ?? []).map((batch) => {
        if (typeof batch.batchStock === 'number' && Number.isFinite(batch.batchStock)) return batch;
        const stock = stockById.get(batch.batchId);
        if (stock == null || !Number.isFinite(stock)) return batch;
        allocationChanged = true;
        anyChanged = true;
        return { ...batch, batchStock: stock };
      });
      return allocationChanged ? { ...allocation, batches } : allocation;
    });

    if (anyChanged) onChange(next);
  }, [warehouseBatchesBySku, componentBatches, onChange, readOnly]);

  useEffect(() => {
    const missing: Array<{ sku: string; batchId: string }> = [];
    for (const allocation of componentBatches) {
      for (const batch of allocation.batches ?? []) {
        const key = `${allocation.sku}::${batch.batchId}`;
        if (String(batch.barcode ?? '').trim()) {
          barcodeFetchAttemptedRef.current.delete(key);
          continue;
        }
        if (!batch.batchId) continue;
        // Після масового fill партії замінюються без ШК — дозволяємо повторний запит.
        barcodeFetchAttemptedRef.current.delete(key);
        missing.push({ sku: allocation.sku, batchId: batch.batchId });
      }
    }
    if (missing.length === 0) return;

    let cancelled = false;
    void (async () => {
      const barcodeByKey = new Map<string, string>();
      await Promise.all(missing.map(async ({ sku, batchId }) => {
        const key = `${sku}::${batchId}`;
        try {
          const barcode = await fetchBarcodeForBatch(sku, batchId);
          if (barcode) barcodeByKey.set(key, barcode);
        } finally {
          barcodeFetchAttemptedRef.current.add(key);
        }
      }));
      if (cancelled || barcodeByKey.size === 0) return;

      const next = componentBatches.map((allocation) => {
        const batches = (allocation.batches ?? []).map((batch) => {
          const key = `${allocation.sku}::${batch.batchId}`;
          const barcode = barcodeByKey.get(key);
          if (!barcode || String(batch.barcode ?? '').trim()) return batch;
          return { ...batch, barcode };
        });
        return { ...allocation, batches };
      });

      onChange(next);
    })();

    return () => {
      cancelled = true;
    };
  }, [componentBatches, onChange]);

  const updateSkuBatches = (sku: string, nextBatches: ReleaseComponentBatch[]) => {
    const others = componentBatches.filter((allocation) => allocation.sku !== sku);
    if (nextBatches.length === 0) {
      onChange(others);
      return;
    }
    onChange([...others, { sku, batches: nextBatches }]);
  };

  const openDrawer = (sku: string, batchIndex: number | null) => {
    autoSelectBatchKeyRef.current = null;
    setActiveSku(sku);
    setEditingBatchIndex(batchIndex);
    setIsDrawerOpen(true);
    void fetchBatches(
      sku,
      selectedDateTime ?? new Date(),
      firmId ?? undefined,
      false,
      storageId ?? undefined,
      { includeNonPositiveQty: allowNegativeBatches },
    );
  };

  const handleBatchSelect = async (batch: BatchNumber) => {
    if (!activeSku) return;

    const current = [...(allocationMap.get(activeSku) ?? [])];
    const component = components.find((row) => row.sku === activeSku);
    const barcode = await fetchBarcodeForBatch(activeSku, batch.batchId);
    const duplicate = current.some(
      (item, index) => index !== editingBatchIndex && item.batchId === batch.batchId,
    );
    if (duplicate) {
      ToastService.show({
        title: 'Партія вже додана',
        description: `Партія ${batch.batchNumber} вже є в списку`,
        color: 'warning',
      });
      setIsDrawerOpen(false);
      return;
    }

    const batchStock = allowNegativeBatches
      ? Number(batch.quantity ?? 0)
      : Math.max(0, Number(batch.quantity ?? 0));
    const isNewBatch = editingBatchIndex === -1 || editingBatchIndex === null;

    if (isNewBatch) {
      const otherAllocated = getOtherAllocatedQuantity(current, -1);
      const suggestedQuantity = component
        ? getSuggestedBatchQuantity(
          batchStock,
          component.requiredQuantity,
          otherAllocated,
          limitByStockOnly,
          allowNegativeBatches,
        )
        : Math.max(0, batchStock);

      current.push({
        batchId: batch.batchId,
        batchNumber: batch.batchNumber,
        quantity: suggestedQuantity,
        batchStock,
        barcode: barcode ?? undefined,
      });
    } else if (editingBatchIndex !== null) {
      const otherAllocated = getOtherAllocatedQuantity(current, editingBatchIndex);
      const maxQuantity = component
        ? getBatchQuantityMax(
          { batchId: batch.batchId, quantity: 0, batchStock },
          component.requiredQuantity,
          otherAllocated,
          [],
          limitByStockOnly,
          isCorrectionUnkitStep,
        )
        : Math.max(0, batchStock);
      const previousQuantity = Number(current[editingBatchIndex]?.quantity ?? 0);

      current[editingBatchIndex] = {
        ...current[editingBatchIndex],
        batchId: batch.batchId,
        batchNumber: batch.batchNumber,
        batchStock,
        barcode: barcode ?? undefined,
        quantity: Math.min(previousQuantity, maxQuantity),
      };
    }

    updateSkuBatches(activeSku, current);
    setIsDrawerOpen(false);
    setEditingBatchIndex(null);
    setActiveSku(null);
    autoSelectBatchKeyRef.current = null;
  };

  useEffect(() => {
    if (correctionMode || operationKey !== 'goodKit') return;
    if (!isDrawerOpen || !activeSku || loading || editingBatchIndex !== -1) return;
    if (selectableBatches.length !== 1) return;

    const batch = selectableBatches[0];
    const attemptKey = `${activeSku}:${batch.batchId}`;
    if (autoSelectBatchKeyRef.current === attemptKey) return;
    autoSelectBatchKeyRef.current = attemptKey;

    void handleBatchSelect(batch);
  }, [correctionMode, operationKey, isDrawerOpen, activeSku, loading, editingBatchIndex, selectableBatches]);

  const handleQuantityChange = (sku: string, index: number, quantity: number, max?: number) => {
    const current = [...(allocationMap.get(sku) ?? [])];
    if (!current[index]) return;
    const clamped = max !== undefined
      ? Math.max(0, Math.min(max, quantity))
      : Math.max(0, quantity);
    current[index] = { ...current[index], quantity: clamped };
    updateSkuBatches(sku, current);
  };

  const handleDeleteBatch = () => {
    if (!deleteConfirm) return;
    const current = [...(allocationMap.get(deleteConfirm.sku) ?? [])];
    current.splice(deleteConfirm.index, 1);
    updateSkuBatches(deleteConfirm.sku, current);
    setDeleteConfirm(null);
  };

  const handleFifoSelect = async () => {
    if (fifoLoading || readOnly || components.length === 0) return;

    const skus = [...new Set(components.map((component) => component.sku.trim()).filter(Boolean))];
    if (skus.length === 0) return;

    setFifoLoading(true);
    try {
      const url = buildReleaseBulkBatchNumbersUrl(skus, {
        firmId,
        storageId,
        selectedDateTime,
        includeNonPositiveQty: allowNegativeBatches,
      });

      const response = await fetch(url.toString(), { credentials: 'include' });
      const json = await response.json().catch(() => null) as {
        success?: boolean;
        error?: string;
        batchesBySku?: Record<string, BatchNumber[]>;
      } | null;

      if (!response.ok || !json?.success || !json.batchesBySku) {
        throw new Error(json?.error || 'Не вдалося завантажити партії');
      }

      setWarehouseBatchesBySku(json.batchesBySku);

      const now = selectedDateTime ?? new Date();
      const next: ReleaseComponentAllocation[] = [];
      const shortfall: string[] = [];

      for (const component of components) {
        const selectable = (json.batchesBySku[component.sku] ?? []).filter((batch) => {
          const label = String(batch.batchNumber ?? batch.batchId ?? '').trim();
          if (hideAutoGeneratedBatches && isAutoGeneratedSystemBatch(label)) return false;
          if (!canSetTpGoodsGoodPart({ batchId: batch.batchId, batchNumber: batch.batchNumber })) return false;
          return Number(batch.quantity ?? 0) > 0;
        });

        const allocated = allocateBatchesFifo(selectable, component.requiredQuantity, now);
        const covered = allocated.reduce((sum, batch) => sum + batch.quantity, 0);
        if (component.requiredQuantity > 0 && covered + 0.0001 < component.requiredQuantity) {
          shortfall.push(component.name || component.sku);
        }
        if (allocated.length === 0) continue;

        next.push({
          sku: component.sku,
          batches: allocated.map((batch) => ({
            batchId: batch.batchId,
            batchNumber: batch.batchNumber,
            quantity: batch.quantity,
            batchStock: batch.batchStock,
          })),
        });
      }

      onChange(next);

      if (next.length === 0) {
        ToastService.show({
          title: 'Партій не знайдено',
          description: 'На складі немає доступних партій для автовибору',
          color: 'warning',
        });
        return;
      }

      if (shortfall.length > 0) {
        ToastService.show({
          title: 'FIFO: не вистачило залишку',
          description: shortfall.join(', '),
          color: 'warning',
        });
        return;
      }

      ToastService.show({
        title: 'Партії обрано за FIFO',
        description: 'Старіші партії підставлені першими',
        color: 'success',
      });
    } catch (error) {
      ToastService.show({
        title: 'Не вдалося обрати партії',
        description: error instanceof Error ? error.message : 'Невідома помилка',
        color: 'danger',
      });
    } finally {
      setFifoLoading(false);
    }
  };

  const addedBatchKeys = new Set<string>();
  if (activeSku) {
    for (const batch of allocationMap.get(activeSku) ?? []) {
      addedBatchKeys.add(`${batch.batchId}:${storageId ?? ''}`);
    }
  }

  const showBulkFillActions = correctionMode
    && correctionStep === 1
    && Boolean(onFillAllBatches);

  if (components.length === 0) return null;

  return (
    <>
      <div className="mb-2 flex items-center justify-between gap-3">
        <h3 className="font-medium text-gray-800">Компоненти набору</h3>
        <span className="text-xs text-gray-500">Місце зберігання: <b>{storageName ?? storageId ?? '—'}</b></span>
      </div>

      <Card className="rounded-xl border border-gray-200 bg-white p-4 mb-6">
        {!correctionMode && (
          <Button
            size="lg"
            variant="flat"
            color="success"
            data-btn-tone="success-flat"
            className="mb-4 py-3 h-auto border-1 border-success-500/20 data-[pressed=true]:scale-[0.99] flex-wrap"
            isLoading={fifoLoading}
            spinner={<Spinner size="sm" color="success" />}
            isDisabled={readOnly || fifoLoading}
            onPress={() => {
              void handleFifoSelect();
            }}
            endContent={<span className="text-sm">(старіші партії йдуть першими)</span>}
            disableRipple={true}
          >
            Обрати партії автоматично за FIFO алгоритмом
          </Button>
        )}
        <div className="space-y-3">
          {components.map((component) => {
            const skuBatches = allocationMap.get(component.sku) ?? [];
            const allocated = skuBatches.reduce((sum, batch) => sum + Number(batch.quantity ?? 0), 0);
            const isComplete = Math.abs(allocated - component.requiredQuantity) < 0.0001;
            const availableSkuBatches = filterSelectableWarehouseBatches(
              warehouseBatchesBySku[component.sku] ?? [],
              hideAutoGeneratedBatches,
              allowNegativeBatches,
            );
            const hasAlternativeBatches = hasUnselectedWarehouseBatches(skuBatches, availableSkuBatches);
            const canSwapSingleBatch = !correctionMode
              && isComplete
              && skuBatches.length === 1
              && hasAlternativeBatches;
            const canSwapBatchInRow = !correctionMode
              && isComplete
              && skuBatches.length > 1
              && hasAlternativeBatches;

            return (
              <div key={component.sku} className="overflow-hidden rounded-md border border-gray-200">
                <div className="flex flex-wrap items-start justify-between gap-2 px-3 py-2.5">
                  <div>
                    <div className="font-medium text-gray-900">{component.name || component.sku}</div>
                    <div className="text-xs text-gray-500">SKU: {component.sku}</div>
                  </div>
                  <div className="text-right">
                    <div className={`text-sm font-semibold ${isComplete ? 'text-emerald-700' : 'text-amber-700'}`}>
                      Обрано: {formatPortionQty(allocated)} {!correctionMode && ` / Потрібно: ${formatPortionQty(component.requiredQuantity)}`}
                    </div>
                    {correctionMode ? (
                      (() => {
                        const portionsPerBox = component.portionsPerBox != null && component.portionsPerBox > 0
                          ? component.portionsPerBox
                          : 1;
                        const { boxes, loosePortions } = breakdownStockPortions(allocated, portionsPerBox);
                        return (
                          <div className="mt-1 flex justify-end">
                            <QtyPills boxes={boxes} loose={loosePortions} />
                          </div>
                        );
                      })()
                    ) : component.perSetQuantity != null && (
                      <div className="mt-1 text-xs text-gray-600">
                        В наборі: <strong>{formatPortionQty(component.perSetQuantity)} шт.</strong> / разом: <strong>{formatPortionQty(component.requiredQuantity)} шт.</strong>
                      </div>
                    )}
                  </div>
                </div>

                {skuBatches.length > 0 && (
                  <div className="space-y-2 border-t border-gray-200/75 p-3">
                    {skuBatches.map((batch, index) => {
                      const otherAllocated = getOtherAllocatedQuantity(skuBatches, index);
                      const maxQuantity = getBatchQuantityMax(
                        batch,
                        component.requiredQuantity,
                        otherAllocated,
                        batches,
                        limitByStockOnly,
                        isCorrectionUnkitStep,
                      );
                      const currentQuantity = Number(batch.quantity ?? 0);
                      const batchStock = getBatchStockLimit(batch, batches, allowNegativeBatches);
                      const isBatchStockMax = !isCorrectionUnkitStep
                        && Number.isFinite(batchStock)
                        && batchStock > 0
                        && currentQuantity >= batchStock;
                      const remainingForBatch = Math.max(0, component.requiredQuantity - otherAllocated);
                      const canSetBatchMaxUnkit = isCorrectionUnkitStep
                        && !isComplete
                        && remainingForBatch > 0
                        && currentQuantity < remainingForBatch;
                      const canSetBatchMaxStock = limitByStockOnly
                        && Number.isFinite(batchStock)
                        && batchStock > 0
                        && currentQuantity < batchStock;
                      const canSetBatchMax = canSetBatchMaxUnkit || canSetBatchMaxStock;

                      const barcodeLabel = String(batch.barcode ?? '').trim();
                      const accountingStock = getAccountingBatchStock(
                        batch,
                        [
                          ...(warehouseBatchesBySku[component.sku] ?? []),
                          ...(activeSku === component.sku ? batches : []),
                        ],
                      );

                      return (
                      <div key={`${component.sku}-${batch.batchId}-${index}`} className="flex flex-wrap items-center gap-3 rounded-md pl-3 pr-2 py-2 bg-gray-100">
                        <div className="min-w-[140px] flex-1">
                          <div className="text-sm font-medium text-gray-800">{batch.batchNumber || batch.batchId}</div>
                          <div className="text-xs text-gray-500">
                            ШК: <span className="font-mono text-gray-600">{barcodeLabel || '—'}</span>
                            {accountingStock != null && (
                              <>
                                {' · '}
                                По обліку:{' '}
                                <span
                                  className={`font-semibold tabular-nums ${
                                    accountingStock < 0 ? 'text-danger' : 'text-gray-600'
                                  }`}
                                >
                                  {formatPortionQty(accountingStock)}
                                </span>
                              </>
                            )}
                          </div>
                        </div>
                        <div className="flex items-center gap-2">
                          <ReleaseBatchMovementsButton
                            sku={component.sku}
                            productName={component.name}
                            batchId={batch.batchId}
                            batchLabel={batch.batchNumber || batch.batchId}
                            storageId={storageId}
                          />
                          {!correctionMode && isBatchStockMax && (
                            <span className="text-xs font-medium uppercase tracking-wide text-fuchsia-700/60 bg-fuchsia-300/15 px-1.5 py-0.5 rounded">
                              max
                            </span>
                          )}
                          {canSetBatchMax && (
                            <button
                              type="button"
                              className="text-xs font-medium uppercase tracking-wide text-fuchsia-700/80 bg-fuchsia-300/15 px-1.5 py-0.5 rounded hover:bg-fuchsia-300/25"
                              onClick={() => handleQuantityChange(
                                component.sku,
                                index,
                                canSetBatchMaxUnkit ? remainingForBatch : batchStock,
                                maxQuantity,
                              )}
                            >
                              max
                            </button>
                          )}
                          <StepperInput
                            aria-label="Кількість"
                            value={currentQuantity}
                            max={maxQuantity}
                            onChange={(value) => handleQuantityChange(component.sku, index, value, maxQuantity)}
                            onIncrement={() => handleQuantityChange(component.sku, index, currentQuantity + 1, maxQuantity)}
                            onDecrement={() => handleQuantityChange(component.sku, index, Math.max(0, currentQuantity - 1), maxQuantity)}
                            size="sm"
                            className="w-32"
                            disabled={readOnly}
                          />
                        </div>
                        {!readOnly && (
                          <div className="flex items-center gap-0.5">
                            {canSwapBatchInRow && (
                              <Button
                                variant="light"
                                color="primary"
                                isIconOnly
                                aria-label="Змінити партію"
                                onPress={() => openDrawer(component.sku, index)}
                              >
                                <DynamicIcon name="edit-2" className="h-4 w-4" />
                              </Button>
                            )}
                            <Button
                              variant="light"
                              color="danger"
                              isIconOnly
                              aria-label="Видалити партію"
                              onPress={() => setDeleteConfirm({
                                sku: component.sku,
                                index,
                                batchNumber: batch.batchNumber || batch.batchId,
                              })}
                            >
                              <DynamicIcon name="trash-2" className="h-4 w-4" />
                            </Button>
                          </div>
                        )}
                      </div>
                      );
                    })}
                  </div>
                )}

                {!readOnly && (
                  <div className="flex flex-wrap gap-2 border-t border-gray-200/75 p-3">
                    <Button
                      size="sm"
                      variant="flat"
                      color="primary"
                      data-btn-tone="primary-blue-flat"
                      className="px-3 min-w-12 gap-1 data-[disabled=true]:opacity-50"
                      startContent={<DynamicIcon name="plus" className="h-4 w-4" />}
                      isDisabled={!correctionMode && isComplete}
                      onPress={() => openDrawer(component.sku, -1)}
                    >
                      Додати партію
                    </Button>
                    {canSwapSingleBatch ? (
                      <Button
                        size="sm"
                        variant="flat"
                        color="warning"
                        startContent={<DynamicIcon name="repeat" className="h-4 w-4" />}
                        onPress={() => openDrawer(component.sku, 0)}
                      >
                        Замінити партію
                      </Button>
                    ) : null}
                    {showBulkFillActions && (
                      <Button
                        size="sm"
                        color="success"
                        variant="flat"
                        className="design:btn-success-flat px-3 min-w-12 gap-1"
                        startContent={<DynamicIcon name="plus-circle" className="h-4 w-4" />}
                        onPress={onFillAllBatches}
                      >
                        Додати всі партії
                      </Button>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </Card>

      <BatchNumbersAutocomplete
        batches={selectableBatches}
        isOpen={isDrawerOpen}
        isLoading={loading}
        selectedBatch={
          editingBatchIndex !== null
          && editingBatchIndex !== -1
          && activeSku
            ? (allocationMap.get(activeSku)?.[editingBatchIndex]?.batchNumber ?? '')
            : ''
        }
        selectedStorage={storageId ?? ''}
        selectedDateTime={selectedDateTime ?? new Date()}
        sourceStorage={storageId ?? undefined}
        sourceStorageName={storageName ?? undefined}
        addedBatchKeys={addedBatchKeys}
        portionsPerBox={activePortionsPerBox}
        includeNonPositiveQty={allowNegativeBatches}
        hideAutoGeneratedBatches={hideAutoGeneratedBatches}
        onSelect={handleBatchSelect}
        onClose={() => {
          setIsDrawerOpen(false);
          setEditingBatchIndex(null);
          setActiveSku(null);
        }}
        onRefresh={() => {
          if (!activeSku) return;
          void fetchBatches(
            activeSku,
            selectedDateTime ?? new Date(),
            firmId ?? undefined,
            true,
            storageId ?? undefined,
            { includeNonPositiveQty: allowNegativeBatches },
          );
        }}
        inputRef={inputRef}
      />

      <ConfirmModal
        isOpen={Boolean(deleteConfirm)}
        title="Видалити партію з операції?"
        message={deleteConfirm ? `Партія ${deleteConfirm.batchNumber} буде видалена з поточної операції.` : ''}
        confirmText="Видалити"
        cancelText="Скасувати"
        confirmColor="danger"
        onConfirm={handleDeleteBatch}
        onCancel={() => setDeleteConfirm(null)}
      />
    </>
  );
}
