import { Router } from 'express';
import type { Prisma } from '@prisma/client';
import { prisma } from '../../lib/utils.js';
import { normalizeSetsArray, normalizeReleaseHistoryItems } from './historyNormalize.js';
import { authenticateToken, requirePermission } from '../../middleware/auth.js';
import { dilovodExportFlowService } from '../../services/dilovod/index.js';
import { getDilovodUserId, getDilovodExportErrorMessage, translateDilovodError, getDilovodConfigFromDB } from '../../services/dilovod/DilovodUtils.js';
import { catalogOpsLookup } from '../Products/CatalogOpsLookup.js';
import {
  formatReleaseDocNumber,
  isRebatchSku,
  type ReleaseComponentAllocation,
  type ReleaseComponentBatch,
} from '../../../shared/types/warehouseRelease.js';
import {
  isAutoGeneratedSystemBatch,
  isUsableDilovodBatchId,
} from '../../../shared/utils/dilovodBatchId.js';
import {
  buildTpGoodsFromBatches,
  mergeBatchesIntoComponentsSnapshot,
  validateReleaseBatches,
} from './releaseBatchValidation.js';
import { productsCatalogService } from '../Products/ProductsCatalogService.js';
import { warehouseBatchesService } from './WarehouseBatchesService.js';
import { ROLES } from '../../../shared/constants/roles.js';
import { canEditWarehouseReleaseHistory } from '../../../shared/utils/releaseHistoryAccess.js';
import { warehouseReleaseAuditService } from './WarehouseReleaseAuditService.js';
import {
  appendWarehouseReleaseDilovodRemark,
  buildWarehouseReleaseEditRemarkNote,
  extractDilovodRemarkFromReleaseItems,
} from '../../../shared/utils/warehouseReleaseRemark.js';
import {
  buildReleaseSendError,
  extractReleaseSendErrorFromItems,
  formatReleaseSendErrorRaw,
  type ReleaseSendErrorInfo,
} from '../../../shared/utils/releaseSendError.js';
import {
  createCorrectionSessionId,
  isReleaseBatchCorrection,
} from '../../../shared/utils/releaseBatchCorrection.js';

const router = Router();
const RELEASE_STATUS_CREATED = 'created';
const RELEASE_STATUS_SEND_FAILED = 'send_failed';
const RELEASE_ACTIVE_STATUSES = [RELEASE_STATUS_CREATED, RELEASE_STATUS_SEND_FAILED];
const warehouseOperate = requirePermission('warehouse', 'operate', 'Створювати/відправляти складські документи');
const warehouseHistoryDelete = requirePermission('warehouse', 'history.delete', 'Видаляти історію складських документів');

const SET_RELEASE_DOC_ID = 'documents.goodWriteOff';
const SET_RELEASE_DOC_MODE_KIT = '1004000000000305';
const SET_RELEASE_DOC_MODE_UNKIT = '1004000000000306';
function formatLocalDate(date: Date): string {
  const pad = (value: number): string => String(value).padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`;
}

/** Dilovod balance може повертати кілька рядків на одну пару batchId+storage (різні firm). */
function dedupeBatchesByStorage<T extends { batchId: string; storage?: string }>(batches: T[]): T[] {
  const seen = new Set<string>();
  const result: T[] = [];
  for (const batch of batches) {
    const key = `${String(batch.batchId ?? '').trim()}:${String(batch.storage ?? '').trim()}`;
    if (seen.has(key)) continue;
    seen.add(key);
    result.push(batch);
  }
  return result;
}

function parseLocalDate(value: unknown): Date | null {
  if (typeof value !== 'string' || value.trim() === '') {
    return null;
  }

  const trimmed = value.trim();

  const localMatch = /^(\d{4})-(\d{2})-(\d{2})[ T](\d{2}):(\d{2})(?::(\d{2}))?$/.exec(trimmed);
  if (localMatch) {
    const [, year, month, day, hours, minutes, seconds] = localMatch;
    return new Date(
      Number(year),
      Number(month) - 1,
      Number(day),
      Number(hours),
      Number(minutes),
      Number(seconds ?? '0'),
    );
  }

  const parsed = new Date(trimmed);
  return Number.isNaN(parsed.getTime()) ? null : parsed;
}

async function resolveKitGoodId(setSku: string | number | undefined, kitGood: string | number | undefined): Promise<string | null> {
  const explicitKitGood = kitGood != null && String(kitGood).trim() !== '' ? String(kitGood).trim() : '';
  if (explicitKitGood) {
    return explicitKitGood;
  }

  const normalizedSku = setSku != null ? String(setSku).trim() : '';
  if (!normalizedSku) {
    return null;
  }

  const product = await catalogOpsLookup.getBySku(normalizedSku);
  return product?.dilovodId?.trim() || null;
}

function buildReleaseHistoryComment(remark: unknown, comment: unknown): string | null {
  const values = [remark, comment]
    .map((value) => String(value ?? '').trim())
    .filter((value) => value.length > 0);

  const uniqueValues = Array.from(new Set(values));
  return uniqueValues.length > 0 ? uniqueValues.join(' | ') : null;
}

type ReleaseSetSourceItem = {
  set_sku?: string | number | null;
  setSku?: string | number | null;
  sku?: string | number | null;
  quantity?: number | string | null;
  components_snapshot?: unknown;
  components_quantity_mode?: string | null;
  componentsQuantityMode?: string | null;
};

type DirectSetComponent = {
  sku: string;
  name: string | null;
  quantity: number;
};

type SnapshotQuantityMode = 'per_set' | 'total';

function resolveSnapshotQuantityMode(item: ReleaseSetSourceItem): SnapshotQuantityMode {
  const raw = item.components_quantity_mode ?? item.componentsQuantityMode;
  return String(raw ?? '').toLowerCase() === 'total' ? 'total' : 'per_set';
}

function parseSetComponents(rawSet: unknown): Array<{ id?: string | number | null; sku?: string | number | null; quantity?: number | string | null; name?: string | null }> {
  if (Array.isArray(rawSet)) {
    return rawSet;
  }

  if (typeof rawSet === 'string') {
    try {
      const parsed = JSON.parse(rawSet);
      return Array.isArray(parsed) ? parsed : [];
    } catch (error) {
      console.warn('[SetRelease] Failed to parse set JSON:', error);
      return [];
    }
  }

  return [];
}

/**
 * Snapshot після normalizeReleaseHistoryItems зберігає quantity як TOTAL + quantity_per_set.
 * UI/preview може передавати per_set. Не множимо total повторно на kitQty (377×377 → 142129).
 */
function normalizeDirectComponentsFromSnapshot(
  snapshot: unknown,
  parentQty: number,
  quantityMode: SnapshotQuantityMode = 'per_set',
): DirectSetComponent[] {
  if (!Array.isArray(snapshot) || parentQty <= 0) {
    return [];
  }

  const components: DirectSetComponent[] = [];
  for (const component of snapshot) {
    if (!component) continue;
    const rawSku = component.id ?? component.sku ?? component.code ?? null;
    const sku = String(rawSku ?? '').trim();
    if (!sku) continue;

    const perSetRaw = Number(component.quantity_per_set ?? component.quantityPerSet);
    const rawQty = Number(component.quantity ?? component.qty ?? 0);
    let totalQuantity: number;
    if (Number.isFinite(perSetRaw) && perSetRaw > 0) {
      totalQuantity = perSetRaw * parentQty;
    } else if (quantityMode === 'total') {
      totalQuantity = rawQty;
    } else {
      const perSet = Number.isFinite(rawQty) && rawQty > 0 ? rawQty : 1;
      totalQuantity = perSet * parentQty;
    }
    if (!Number.isFinite(totalQuantity) || totalQuantity <= 0) continue;

    components.push({
      sku,
      name: component.name ?? component.title ?? null,
      quantity: totalQuantity,
    });
  }

  return components;
}

async function collectFirstLevelComponents(items: ReleaseSetSourceItem[]): Promise<Record<string, DirectSetComponent>> {
  const aggregated: Record<string, DirectSetComponent> = {};

  for (const item of items) {
    const sku = String(item.set_sku ?? item.setSku ?? item.sku ?? '').trim();
    const quantity = Number(item.quantity ?? 0);
    if (!sku || !Number.isFinite(quantity) || quantity <= 0) {
      continue;
    }

    const quantityMode = resolveSnapshotQuantityMode(item);
    let directComponents = normalizeDirectComponentsFromSnapshot(
      item.components_snapshot,
      quantity,
      quantityMode,
    );

    if (directComponents.length === 0) {
      const product = await catalogOpsLookup.getBySku(sku);
      const setData = parseSetComponents(product?.set);
      if (setData.length === 0) {
        if (product?.dilovodId) {
          if (!aggregated[sku]) {
            aggregated[sku] = { sku, name: product?.name ?? null, quantity: 0 };
          }
          aggregated[sku].quantity += quantity;
        }
        continue;
      }

      directComponents = setData
        .map((component) => {
          const componentSku = String(component.id ?? component.sku ?? '').trim();
          if (!componentSku) return null;
          const componentQty = Number(component.quantity ?? 1);
          if (!Number.isFinite(componentQty) || componentQty <= 0) return null;
          return {
            sku: componentSku,
            name: component.name ?? null,
            quantity: componentQty * quantity,
          };
        })
        .filter((component): component is DirectSetComponent => component !== null);
    }

    for (const component of directComponents) {
      if (!aggregated[component.sku]) {
        aggregated[component.sku] = { sku: component.sku, name: component.name ?? null, quantity: 0 };
      }
      if (!aggregated[component.sku].name && component.name) {
        aggregated[component.sku].name = component.name;
      }
      aggregated[component.sku].quantity += component.quantity;
    }
  }

  return aggregated;
}

function isSelectableReleaseBatch(
  batch: Pick<ReleaseComponentBatch, 'batchId' | 'batchNumber' | 'quantity'>,
  options?: { excludeAutoGenerated?: boolean },
): boolean {
  const batchId = String(batch?.batchId ?? '').trim();
  const quantity = Number(batch?.quantity ?? 0);
  if (!batchId || !Number.isFinite(quantity) || quantity <= 0) return false;
  if (options?.excludeAutoGenerated === false) return true;
  const label = batch?.batchNumber ? String(batch.batchNumber).trim() : batchId;
  return !isAutoGeneratedSystemBatch(label);
}

function parseComponentBatches(
  raw: unknown,
  options?: { excludeAutoGenerated?: boolean },
): ReleaseComponentAllocation[] {
  if (!Array.isArray(raw)) return [];
  return raw
    .map((allocation) => {
      const sku = String(allocation?.sku ?? '').trim();
      const batches = Array.isArray(allocation?.batches)
        ? allocation.batches
            .map((batch: ReleaseComponentBatch) => ({
              batchId: String(batch?.batchId ?? '').trim(),
              batchNumber: batch?.batchNumber ? String(batch.batchNumber).trim() : undefined,
              quantity: Number(batch?.quantity ?? 0),
            }))
            .filter((batch) => isSelectableReleaseBatch(batch, options))
        : [];
      if (!sku || batches.length === 0) return null;
      return { sku, batches };
    })
    .filter((allocation): allocation is ReleaseComponentAllocation => allocation !== null);
}

function extractComponentBatchesFromReleaseRecord(record: {
  items?: unknown;
}): ReleaseComponentAllocation[] {
  const items = Array.isArray(record.items) ? record.items : [];
  const firstItem = items[0];
  if (!firstItem || typeof firstItem !== 'object') return [];

  const direct = parseComponentBatches((firstItem as { component_batches?: unknown }).component_batches);
  if (direct.length > 0) return direct;

  const snapshot = (firstItem as { components_snapshot?: unknown }).components_snapshot;
  if (!Array.isArray(snapshot)) return [];

  const allocations: ReleaseComponentAllocation[] = [];
  for (const component of snapshot) {
    const sku = String(component?.id ?? component?.sku ?? component?.code ?? '').trim();
    const batches = Array.isArray(component?.batches)
      ? component.batches
          .map((batch: ReleaseComponentBatch) => ({
            batchId: String(batch?.batchId ?? '').trim(),
            batchNumber: batch?.batchNumber ? String(batch.batchNumber).trim() : undefined,
            quantity: Number(batch?.quantity ?? 0),
          }))
          .filter(isSelectableReleaseBatch)
      : [];
    if (sku && batches.length > 0) {
      allocations.push({ sku, batches });
    }
  }
  return allocations;
}

function shouldExcludeAutoGeneratedBatches(correctionSessionId: unknown): boolean {
  return !String(correctionSessionId ?? '').trim();
}

function formatCorrectionBatchName(date = new Date()): string {
  const pad = (value: number): string => String(value).padStart(2, '0');
  return `Коригування обліку ${pad(date.getDate())}.${pad(date.getMonth() + 1)}.${date.getFullYear()}`;
}

function collectComponentBatchIds(allocations: ReleaseComponentAllocation[]): string[] {
  const ids: string[] = [];
  for (const allocation of allocations) {
    for (const batch of allocation.batches ?? []) {
      const batchId = String(batch?.batchId ?? '').trim();
      if (isUsableDilovodBatchId(batchId)) {
        ids.push(batchId);
      }
    }
  }
  return ids;
}

function isRegularKitRelease(input: {
  operationType: 'kit' | 'unkit';
  setSku: string;
  correctionSessionId: unknown;
}): boolean {
  if (input.operationType !== 'kit') return false;
  if (isRebatchSku(input.setSku)) return false;
  const sessionId = String(input.correctionSessionId ?? '').trim();
  return sessionId.length === 0;
}

type ReleaseHistoryPayload = {
  itemsWithNames: any[];
  totalQuantity: number;
  historyComment: string | null;
  resolvedOperationType: 'kit' | 'unkit';
  resolvedOperDate: Date;
  setSku: string | null;
};

async function prepareReleaseHistoryPayload(params: {
  items: any[];
  componentBatches: ReleaseComponentAllocation[];
  remark: unknown;
  comment: unknown;
  operationType?: unknown;
  operDate?: unknown;
  date?: unknown;
  correctionSessionId?: unknown;
}): Promise<ReleaseHistoryPayload> {
  const {
    items,
    componentBatches,
    remark,
    comment,
    operationType,
    operDate,
    date,
    correctionSessionId,
  } = params;

  const skus = Array.from(new Set(items.map((it: any) => String(it.set_sku || it.setSku || it.sku || '').trim()).filter((s: string) => s)));
  let nameMap: Record<string, string> = {};
  if (skus.length > 0) {
    const found = await catalogOpsLookup.getBySkus(skus);
    for (const product of catalogOpsLookup.listUnique(found)) {
      nameMap[String(product.sku)] = product.name || '';
    }
  }

  const normalizedItems = normalizeReleaseHistoryItems(items);
  const inheritedCorrectionSession = extractCorrectionSessionIdFromItems(normalizedItems);
  let resolvedCorrectionSession = correctionSessionId != null && String(correctionSessionId).trim() !== ''
    ? String(correctionSessionId).trim()
    : inheritedCorrectionSession;

  const totalQuantityPreview = Number(
    normalizedItems.reduce((acc: number, it: any) => acc + (Number(it.quantity) || 0), 0),
  ) || 0;
  const historyCommentPreview = buildReleaseHistoryComment(remark, comment);
  // Якщо коментар/REBATCH вказує на коригування, а сесії немає — створюємо, щоб історія не губила маркер.
  if (
    !resolvedCorrectionSession
    && isReleaseBatchCorrection({
      comment: historyCommentPreview,
      setSku: normalizedItems[0]?.set_sku ?? normalizedItems[0]?.setSku,
      items: normalizedItems,
    })
  ) {
    resolvedCorrectionSession = createCorrectionSessionId();
  }

  const itemsWithNames = normalizedItems.map((it: any) => {
    const sku = String(it.set_sku || it.setSku || it.sku || '').trim();
    const mergedSnapshot = mergeBatchesIntoComponentsSnapshot(
      it.components_snapshot ?? it.componentsSnapshot,
      componentBatches,
    );
    return {
      ...it,
      name: it.name ?? nameMap[sku] ?? null,
      components_snapshot: mergedSnapshot,
      component_batches: componentBatches,
      correction_session_id: resolvedCorrectionSession,
    };
  });

  const totalQuantity = totalQuantityPreview;
  const historyComment = historyCommentPreview;
  const resolvedOperationType = String(operationType ?? 'kit').trim() === 'unkit' ? 'unkit' : 'kit';
  const resolvedOperDate = parseLocalDate(operDate ?? date) ?? new Date();

  return {
    itemsWithNames,
    totalQuantity,
    historyComment,
    resolvedOperationType,
    resolvedOperDate,
    setSku: itemsWithNames[0]?.set_sku ?? null,
  };
}

async function projectReleaseDocNumber(): Promise<string> {
  const aggregate = await prisma.warehouseReleaseSet.aggregate({ _max: { id: true } });
  return formatReleaseDocNumber((aggregate._max.id ?? 0) + 1);
}

async function allocateReleaseDocNumber(params: {
  createdBy: number;
  setSku: string | null;
  quantity: number;
  storageId: string | null;
  firmId: string | null;
  operationType: 'kit' | 'unkit';
  operDate: Date;
}): Promise<{ releaseId: number; docNumber: string }> {
  const placeholder = await prisma.warehouseReleaseSet.create({
    data: {
      internalDocNumber: `TMP-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
      setSku: params.setSku,
      quantity: params.quantity,
      items: [],
      storageId: params.storageId,
      firmId: params.firmId,
      operationType: params.operationType,
      status: 'pending',
      createdBy: params.createdBy,
      operDate: params.operDate,
    },
  });

  const docNumber = formatReleaseDocNumber(placeholder.id);
  await prisma.warehouseReleaseSet.update({
    where: { id: placeholder.id },
    data: { internalDocNumber: docNumber },
  });

  return { releaseId: placeholder.id, docNumber };
}

async function discardFailedReleasePlaceholder(releaseId: number | null): Promise<void> {
  if (!releaseId) return;
  try {
    const row = await prisma.warehouseReleaseSet.findUnique({ where: { id: releaseId } });
    if (!row) return;
    if (row.dilovodDocId && String(row.dilovodDocId).trim() !== '') return;
    if (row.status === RELEASE_STATUS_CREATED || row.status === RELEASE_STATUS_SEND_FAILED) return;
    const items = Array.isArray(row.items) ? row.items : [];
    if (items.length > 0) return;
    await prisma.warehouseReleaseSet.delete({ where: { id: releaseId } });
  } catch (error) {
    console.warn('[SetRelease] Failed to discard failed release placeholder:', error);
  }
}

function extractStoredKitOutputBatch(items: unknown): {
  batchId: string | null;
  batchNumber: string;
  barcode: string | null;
  created: boolean;
  expiration: string | null;
} | null {
  if (!Array.isArray(items) || items.length === 0) return null;
  const first = items[0];
  if (!first || typeof first !== 'object') return null;
  const raw = (first as { kit_output_batch?: unknown }).kit_output_batch;
  if (!raw || typeof raw !== 'object') return null;
  const batch = raw as Record<string, unknown>;
  const batchId = batch.batchId != null ? String(batch.batchId).trim() : '';
  const batchNumber = String(batch.batchNumber ?? '').trim();
  if (!batchId && !batchNumber) return null;
  return {
    batchId: batchId || null,
    batchNumber,
    barcode: batch.barcode != null ? String(batch.barcode) : null,
    created: Boolean(batch.created),
    expiration: batch.expiration != null ? String(batch.expiration) : null,
  };
}

function extractSendErrorFromReleaseItems(items: unknown): ReleaseSendErrorInfo | null {
  return extractReleaseSendErrorFromItems(items);
}

function extractCorrectionSessionIdFromItems(items: unknown): string | null {
  if (!Array.isArray(items) || items.length === 0) return null;
  const first = items[0];
  if (!first || typeof first !== 'object') return null;
  const value = String((first as { correction_session_id?: unknown }).correction_session_id ?? '').trim();
  return value || null;
}

async function patchReleaseSendError(
  releaseId: number,
  existingItems: unknown,
  sendError: ReleaseSendErrorInfo,
): Promise<boolean> {
  if (!Array.isArray(existingItems) || existingItems.length === 0) return false;
  const nextItems = existingItems.map((item, index) => {
    if (index !== 0 || !item || typeof item !== 'object') return item;
    return {
      ...(item as Record<string, unknown>),
      dilovod_send_error: sendError,
    };
  });
  await prisma.warehouseReleaseSet.update({
    where: { id: releaseId },
    data: {
      items: nextItems as Prisma.InputJsonValue,
      status: RELEASE_STATUS_SEND_FAILED,
    },
  });
  return true;
}

function releaseItemsToSendSource(items: unknown): ReleaseSetSourceItem[] {
  if (!Array.isArray(items)) return [];
  return items
    .filter((item) => item && typeof item === 'object')
    .map((item) => {
      const row = item as ReleaseSetSourceItem & { setSku?: string };
      return {
        set_sku: row.set_sku ?? row.setSku,
        quantity: row.quantity,
        components_snapshot: row.components_snapshot,
        components_quantity_mode: row.components_quantity_mode ?? row.componentsQuantityMode ?? 'total',
      };
    });
}

async function getReleaseEditorLabel(userId: number | null): Promise<string> {
  if (!userId) return 'користувач';
  try {
    const user = await prisma.user.findUnique({
      where: { id: userId },
      select: { name: true, email: true },
    });
    if (!user) return 'користувач';
    const name = String(user.name ?? '').trim();
    return name || String(user.email ?? '').trim() || 'користувач';
  } catch {
    return 'користувач';
  }
}

async function persistFailedReleaseAttempt(
  releaseId: number,
  params: {
    historyPayload: ReleaseHistoryPayload;
    storageId: string | null;
    firmId: string | null;
    sendError: ReleaseSendErrorInfo;
    kitOutputBatch?: Awaited<ReturnType<typeof warehouseBatchesService.ensureKitOutputBatch>> | null;
    dilovodRemark?: string | null;
  },
): Promise<void> {
  const itemsWithMeta = params.historyPayload.itemsWithNames.map((item, index) => {
    if (index !== 0) return item;
    return {
      ...item,
      dilovod_send_error: params.sendError,
      ...(params.kitOutputBatch ? { kit_output_batch: params.kitOutputBatch } : {}),
      ...(params.dilovodRemark ? { dilovod_remark: params.dilovodRemark } : {}),
    };
  });

  await finalizeReleaseRecord(releaseId, {
    ...params.historyPayload,
    itemsWithNames: itemsWithMeta,
    storageId: params.storageId,
    firmId: params.firmId,
    dilovodDocId: null,
    status: RELEASE_STATUS_SEND_FAILED,
  });
}

async function syncWarehouseReleaseToDilovod(input: {
  record: {
    id: number;
    dilovodDocId: string | null;
    items: unknown;
    storageId: string | null;
    firmId: string | null;
    operationType: string;
    internalDocNumber: string | null;
  };
  operDate: Date;
  quantity: number;
  setSku: string | null;
  remarkNote: string;
}): Promise<{ success: boolean; error?: string; dilovodResponse?: unknown; remark?: string }> {
  const dilovodDocId = input.record.dilovodDocId != null ? String(input.record.dilovodDocId).trim() : '';
  if (!dilovodDocId) {
    return { success: true };
  }

  const setSku = String(input.setSku ?? '').trim();
  const resolvedKitGood = await resolveKitGoodId(setSku, undefined);
  if (!resolvedKitGood) {
    return { success: false, error: 'Не вдалося визначити ID набору в Dilovod для оновлення' };
  }

  const sourceItems = releaseItemsToSendSource(input.record.items);
  const componentBatches = extractComponentBatchesFromReleaseRecord({ items: input.record.items });
  const expandedComponents = await collectFirstLevelComponents(sourceItems);
  const { loadDilovodWarehouseDefaults } = await import('../../services/dilovod/DilovodWarehouseDefaults.js');
  const warehouseDefaults = await loadDilovodWarehouseDefaults();

  const expandedList = Object.values(expandedComponents);
  const skus = expandedList.map((component) => component.sku).filter(Boolean);
  const found = skus.length ? await catalogOpsLookup.getBySkus(skus) : new Map();
  const skuToProduct = new Map(catalogOpsLookup.listUnique(found).map((product) => [product.sku, product]));
  const skuToDilovodId = new Map<string, string>();
  const skuToHasNestedSet = new Map<string, boolean>();

  for (const [sku, product] of skuToProduct.entries()) {
    if (!product?.dilovodId) continue;
    skuToDilovodId.set(sku, product.dilovodId);
    const hasNestedSet = Array.isArray(product.set)
      ? product.set.length > 0
      : typeof product.set === 'string'
        ? String(product.set).trim().length > 0
        : Boolean(product.set);
    skuToHasNestedSet.set(sku, hasNestedSet);
  }

  const { tpGoods } = buildTpGoodsFromBatches(
    expandedList,
    skuToDilovodId,
    skuToHasNestedSet,
    componentBatches,
    warehouseDefaults,
  );

  const storedKitBatch = extractStoredKitOutputBatch(input.record.items);
  const previousRemark = extractDilovodRemarkFromReleaseItems(input.record.items);
  const remark = appendWarehouseReleaseDilovodRemark(previousRemark, input.remarkNote);
  const resolvedDocMode = String(input.record.operationType ?? '').trim() === 'unkit'
    ? SET_RELEASE_DOC_MODE_UNKIT
    : SET_RELEASE_DOC_MODE_KIT;

  const payload: Record<string, unknown> = {
    saveType: 2,
    header: {
      id: dilovodDocId,
      date: formatLocalDate(input.operDate),
      firm: input.record.firmId,
      storage: input.record.storageId,
      posted: 1,
      accCosts: warehouseDefaults.setAccountId,
      docMode: resolvedDocMode,
      kitGood: resolvedKitGood,
      kitQty: input.quantity,
      ...(storedKitBatch?.batchId ? { kitGoodPart: Number(storedKitBatch.batchId) } : {}),
      remark,
    },
    tableParts: { tpGoods },
  };

  const exportResult = await dilovodExportFlowService.send({
    payload,
    dryRun: false,
    warnings: [],
    label: '[SetRelease][patch]',
  });

  if (!exportResult.success) {
    const rawError = exportResult.error || exportResult.dilovodResponse?.error || exportResult.dilovodResponse?.message || 'Dilovod error';
    const message = exportResult.dilovodResponse ? getDilovodExportErrorMessage(exportResult.dilovodResponse) : String(rawError);
    return { success: false, error: message, dilovodResponse: exportResult.dilovodResponse };
  }

  return { success: true, dilovodResponse: exportResult.dilovodResponse, remark };
}

function isWarehouseReleaseHistoryAdmin(req: { user?: { role?: string } }): boolean {
  return req.user?.role === ROLES.ADMIN;
}

function assertCanEditReleaseRecord(
  req: { user?: { role?: string } },
  record: { createdAt: Date },
): void {
  const allowed = canEditWarehouseReleaseHistory({
    isAdmin: isWarehouseReleaseHistoryAdmin(req),
    createdAt: record.createdAt,
  });
  if (!allowed) {
    throw new Error('Редагування цього запису недоступне (лише сьогоднішні записи або роль адміністратора)');
  }
}

function summarizeReleaseBatches(items: unknown): string {
  return extractComponentBatchesFromReleaseRecord({ items })
    .map((allocation) => {
      const batches = (allocation.batches ?? [])
        .map((batch) => `${batch.batchNumber || batch.batchId}×${batch.quantity}`)
        .join(', ');
      return `${allocation.sku}: ${batches}`;
    })
    .join('; ');
}

function preserveReleaseItemMeta(existingItems: unknown, nextItems: any[]): any[] {
  const first = Array.isArray(existingItems) ? existingItems[0] : null;
  const meta = first && typeof first === 'object' ? first as Record<string, unknown> : {};
  return nextItems.map((item, index) => {
    if (index !== 0 || !item || typeof item !== 'object') return item;
    return {
      ...item,
      ...(meta.kit_output_batch ? { kit_output_batch: meta.kit_output_batch } : {}),
      ...(meta.dilovod_remark ? { dilovod_remark: meta.dilovod_remark } : {}),
      ...(meta.dilovod_send_error ? { dilovod_send_error: meta.dilovod_send_error } : {}),
      ...(meta.correction_session_id ? { correction_session_id: meta.correction_session_id } : {}),
    };
  });
}

function buildReleaseUpdateDiff(
  before: {
    operDate: Date;
    comment: string | null;
    quantity: number;
    setSku: string | null;
    batches?: string;
    storageId?: string | null;
    firmId?: string | null;
  },
  after: {
    operDate: Date;
    comment: string | null;
    quantity: number;
    setSku: string | null;
    batches?: string;
    storageId?: string | null;
    firmId?: string | null;
  },
) {
  const changes: Array<{ field: string; from: unknown; to: unknown }> = [];
  const push = (field: string, from: unknown, to: unknown) => {
    if (String(from ?? '') !== String(to ?? '')) {
      changes.push({ field, from, to });
    }
  };
  const sameInstant = Math.abs(before.operDate.getTime() - after.operDate.getTime()) < 1000;
  if (!sameInstant) {
    changes.push({ field: 'operDate', from: before.operDate.toISOString(), to: after.operDate.toISOString() });
  }
  push('comment', before.comment, after.comment);
  push('quantity', before.quantity, after.quantity);
  push('setSku', before.setSku, after.setSku);
  push('batches', before.batches, after.batches);
  push('storageId', before.storageId, after.storageId);
  push('firmId', before.firmId, after.firmId);
  return changes;
}

async function finalizeReleaseRecord(
  releaseId: number,
  params: ReleaseHistoryPayload & {
    storageId: string | null;
    firmId: string | null;
    dilovodDocId: string | null;
    status: string;
  },
) {
  return prisma.warehouseReleaseSet.update({
    where: { id: releaseId },
    data: {
      setSku: params.setSku,
      quantity: params.totalQuantity,
      items: params.itemsWithNames,
      storageId: params.storageId,
      firmId: params.firmId,
      dilovodDocId: params.dilovodDocId,
      operationType: params.resolvedOperationType,
      comment: params.historyComment,
      status: params.status,
      operDate: params.resolvedOperDate,
    },
  });
}

/**
 * POST /api/warehouse/releases
 * Create a new set release record (snapshot)
 */
router.post('/', authenticateToken, warehouseOperate, async (req, res) => {
  try {
    const userId = (req as any).user?.userId || (req as any).user?.id || 0;
    const {
      items,
      storageId,
      firmId,
      comment,
      remark,
      status,
      dilovodDocId,
      operationType,
      operDate,
      date,
      componentBatches,
      correctionSessionId,
    } = req.body;
    if (!Array.isArray(items) || items.length === 0) return res.status(400).json({ success: false, error: 'items required' });
    const parsedComponentBatches = parseComponentBatches(componentBatches, {
      excludeAutoGenerated: shouldExcludeAutoGeneratedBatches(correctionSessionId),
    });

    // Each item expected: { set_sku, quantity, components_snapshot }
    // Accept `firmId` as string (Dilovod uses large string IDs). Store as string to avoid 32-bit overflow.
    const stringFirmId = (firmId != null && String(firmId).trim() !== '') ? String(firmId).trim() : null;
    const historyPayload = await prepareReleaseHistoryPayload({
      items,
      componentBatches: parsedComponentBatches,
      remark,
      comment,
      operationType,
      operDate,
      date,
      correctionSessionId,
    });

    const record = await prisma.warehouseReleaseSet.create({ data: {
      internalDocNumber: `TMP-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
      setSku: historyPayload.setSku,
      quantity: historyPayload.totalQuantity,
      // Prisma `Json` field expects a JS object/array — store as-is, avoid double-stringify
      items: historyPayload.itemsWithNames,
      storageId: storageId ?? null,
      firmId: stringFirmId,
      dilovodDocId: dilovodDocId != null && String(dilovodDocId).trim() !== '' ? String(dilovodDocId).trim() : null,
      operationType: historyPayload.resolvedOperationType,
      comment: historyPayload.historyComment,
      status: status ?? 'created',
      createdBy: Number(userId) || 0,
      operDate: historyPayload.resolvedOperDate,
    } });

    const internalDocNumber = formatReleaseDocNumber(record.id);
    const savedRecord = await prisma.warehouseReleaseSet.update({
      where: { id: record.id },
      data: { internalDocNumber },
    });

    res.json({ success: true, data: savedRecord });
  } catch (error) {
    console.error('[SetRelease] Error saving release:', error);
    res.status(500).json({ success: false, error: error instanceof Error ? error.message : 'Internal server error' });
  }
});

/** POST /api/warehouse/releases/preview - preview expanded components for given sets */
router.post('/preview', authenticateToken, warehouseOperate, async (req, res) => {
  try {
    const { items, componentBatches, correctionSessionId } = req.body;
    if (process.env.NODE_ENV === 'development') console.log('[SetRelease][preview] incoming items:', Array.isArray(items) ? items.length : typeof items);
    if (!Array.isArray(items) || items.length === 0) return res.status(400).json({ success: false, error: 'items required' });

    const expandedComponents = await collectFirstLevelComponents(items as ReleaseSetSourceItem[]);
    const parsedComponentBatches = parseComponentBatches(componentBatches, {
      excludeAutoGenerated: shouldExcludeAutoGeneratedBatches(correctionSessionId),
    });
    const validation = validateReleaseBatches(expandedComponents, parsedComponentBatches, { requireBatches: false });
    const allocationBySku = new Map(parsedComponentBatches.map((allocation) => [allocation.sku, allocation]));

    const result = Object.values(expandedComponents).map((component) => {
      const allocation = allocationBySku.get(component.sku);
      const allocatedQuantity = allocation?.batches?.reduce((sum, batch) => sum + Number(batch.quantity ?? 0), 0) ?? 0;
      return {
        sku: component.sku,
        name: component.name,
        quantity: component.quantity,
        allocatedQuantity,
        batches: allocation?.batches ?? [],
      };
    });

    res.json({
      success: true,
      data: result,
      validation,
    });
  } catch (error) {
    console.error('[SetRelease][preview] error:', error);
    res.status(500).json({ success: false, error: 'Internal server error' });
  }
});

// NOTE: single-item `/check-dilovod` removed — use `/check-dilovod-batch` for batch operations

/** POST /api/warehouse/releases/check-dilovod-batch - batch check dilovod documents */
router.post('/check-dilovod-batch', authenticateToken, warehouseOperate, async (req, res) => {
  try {
    const items = Array.isArray(req.body?.items) ? req.body.items : [];

    if (items.length === 0) return res.status(400).json({ success: false, error: 'items required' });

    const results: Array<any> = [];
    const { dilovodService } = await import('../../services/dilovod/DilovodService.js');

    // Build list of docIds to fetch in batch
    const requestedDocIds = items.map((it: any) => String(it?.dilovodDocId ?? '').trim()).filter((d: string) => d);

    // Fetch documents in chunks via Dilovod batch API
    const docs = await dilovodService.getMovementDocumentsBatch(requestedDocIds).catch((e) => {
      console.warn('[SetRelease][check-dilovod-batch] batch fetch failed', e);
      return [] as any[];
    });

    const docsById: Record<string, any> = {};
    for (const d of Array.isArray(docs) ? docs : []) {
      const id = d?.id != null ? String(d.id) : (d?.ID != null ? String(d.ID) : null);
      if (id) docsById[String(id)] = d;
    }

    for (const it of items) {
      const id = it?.id != null ? Number(it.id) : null;
      const docId = String(it?.dilovodDocId ?? '').trim();
      if (!docId) {
        results.push({ id, dilovodDocId: docId, success: false, error: 'missing dilovodDocId' });
        continue;
      }

      const doc = docsById[docId] || null;

      // If Dilovod did not return data for this id -> consider deleted per user instruction
      const missingInResponse = !doc;

      let delMark = false;
      let success = true;
      let updated = false;

      let remark: string | null = null;
      if (missingInResponse) {
        delMark = true;
      } else {
        const headerDel = doc?.header?.delMark ?? doc?.delMark ?? undefined;
        delMark = headerDel === true || headerDel === 1 || String(headerDel) === '1';
        remark = doc?.remark ?? doc?.header?.remark ?? null;
      }

      if (delMark) {
        // try find by id or dilovodDocId
        try {
          if (id != null) {
            const existing = await prisma.warehouseReleaseSet.findUnique({ where: { id } });
            if (existing) {
              await prisma.warehouseReleaseSet.update({ where: { id }, data: { status: 'deleted' } });
              updated = true;
            } else {
              const created = await prisma.warehouseReleaseSet.create({ data: {
                setSku: null,
                quantity: 0,
                items: [],
                storageId: null,
                firmId: null,
                dilovodDocId: docId,
                comment: null,
                status: 'deleted',
                createdBy: 0,
              } });
              if (created) updated = true;
            }
          } else {
            const existing = await prisma.warehouseReleaseSet.findFirst({ where: { dilovodDocId: docId } });
            if (existing) {
              await prisma.warehouseReleaseSet.update({ where: { id: existing.id }, data: { status: 'deleted' } });
              updated = true;
            } else {
              const created = await prisma.warehouseReleaseSet.create({ data: {
                setSku: null,
                quantity: 0,
                items: [],
                storageId: null,
                firmId: null,
                dilovodDocId: docId,
                comment: null,
                status: 'deleted',
                createdBy: 0,
              } });
              if (created) updated = true;
            }
          }
        } catch (e) {
          console.warn('[SetRelease][check-dilovod-batch] failed to mark/create tombstone', e);
          success = false;
        }
      }

      results.push({ id, dilovodDocId: docId, success, delMark, updated, remark });
    }

    return res.json({ success: true, results });
  } catch (error) {
    console.error('[SetRelease][check-dilovod-batch] Error:', error);
    return res.status(500).json({ success: false, error: error instanceof Error ? error.message : 'Internal server error' });
  }
});

/**
 * POST /api/warehouse/releases/send
 * Формування payload та відправка документа випуску набору в Діловод
 */
router.post('/send', authenticateToken, warehouseOperate, async (req, res) => {
  let releaseId: number | null = null;
  try {
    const {
      kitGood,
      kitQty,
      setSku,
      quantity,
      storageId,
      firmId,
      comment,
      remark,
      date,
      dryRun,
      docMode,
      componentBatches,
      requireBatches,
      createSurplusBatch,
      surplusQuantity,
      surplusGoodId,
      correctionSessionId,
      operationType,
      releaseId: bodyReleaseId,
    } = req.body;
    let items = Array.isArray(req.body?.items) ? req.body.items : [];
    const clientSentItems = items.length > 0;
    const retryReleaseId = Number(bodyReleaseId);
    let retryRecord: Awaited<ReturnType<typeof prisma.warehouseReleaseSet.findUnique>> = null;
    if (Number.isFinite(retryReleaseId) && retryReleaseId > 0) {
      retryRecord = await prisma.warehouseReleaseSet.findUnique({ where: { id: retryReleaseId } });
      if (!retryRecord || retryRecord.status !== RELEASE_STATUS_SEND_FAILED) {
        return res.status(422).json({
          success: false,
          error: 'Повторна відправка доступна лише для записів з помилкою Dilovod',
        });
      }
      releaseId = retryRecord.id;
      if (!clientSentItems) {
        items = releaseItemsToSendSource(retryRecord.items);
      }
    }

    // Retry з історії часто йде з порожньої форми — не затираємо тип/сесію/коментар дефолтами.
    let resolvedCorrectionSessionId = correctionSessionId != null && String(correctionSessionId).trim() !== ''
      ? String(correctionSessionId).trim()
      : null;
    let resolvedDocModeInput = docMode;
    let resolvedOperationTypeInput = operationType;
    let resolvedRemark = remark;
    let resolvedComment = comment;
    let resolvedDate = date;
    let resolvedStorageId = storageId;
    let resolvedFirmIdInput = firmId;

    if (retryRecord && !clientSentItems) {
      const storedOp = String(retryRecord.operationType ?? '').trim() === 'unkit' ? 'unkit' : 'kit';
      resolvedOperationTypeInput = storedOp;
      resolvedDocModeInput = storedOp === 'unkit' ? SET_RELEASE_DOC_MODE_UNKIT : SET_RELEASE_DOC_MODE_KIT;
      if (resolvedRemark == null || String(resolvedRemark).trim() === '') {
        resolvedRemark = extractDilovodRemarkFromReleaseItems(retryRecord.items) ?? retryRecord.comment;
      }
      if (resolvedComment == null || String(resolvedComment).trim() === '') {
        resolvedComment = retryRecord.comment;
      }
      if (resolvedDate == null || String(resolvedDate).trim() === '') {
        resolvedDate = retryRecord.operDate;
      }
      if (resolvedStorageId == null || String(resolvedStorageId).trim() === '') {
        resolvedStorageId = retryRecord.storageId;
      }
      if (resolvedFirmIdInput == null || String(resolvedFirmIdInput).trim() === '') {
        resolvedFirmIdInput = retryRecord.firmId;
      }
    }
    if (!resolvedCorrectionSessionId && retryRecord) {
      resolvedCorrectionSessionId = extractCorrectionSessionIdFromItems(retryRecord.items);
    }

    let parsedComponentBatches = parseComponentBatches(componentBatches, {
      excludeAutoGenerated: shouldExcludeAutoGeneratedBatches(resolvedCorrectionSessionId),
    });
    if (retryRecord && parsedComponentBatches.length === 0) {
      parsedComponentBatches = extractComponentBatchesFromReleaseRecord(retryRecord);
    }
    const resolvedDocMode = String(resolvedDocModeInput ?? SET_RELEASE_DOC_MODE_KIT).trim() === SET_RELEASE_DOC_MODE_UNKIT
      ? SET_RELEASE_DOC_MODE_UNKIT
      : SET_RELEASE_DOC_MODE_KIT;
    const resolvedOperationType = String(resolvedOperationTypeInput ?? '').trim() === 'unkit'
      || resolvedDocMode === SET_RELEASE_DOC_MODE_UNKIT
      ? 'unkit'
      : 'kit';
    const isDryRun = dryRun === true || dryRun === 'true';

    const firstItem = items[0] ?? {};
    const resolvedSetSku = typeof setSku === 'string' && setSku.trim() !== ''
      ? setSku.trim()
      : typeof firstItem.set_sku === 'string'
        ? firstItem.set_sku.trim()
        : typeof firstItem.setSku === 'string'
          ? firstItem.setSku.trim()
          : typeof firstItem.sku === 'string'
            ? firstItem.sku.trim()
            : '';

    const resolvedKitQty = Number(kitQty ?? quantity ?? firstItem.quantity ?? 0);
    if (!resolvedSetSku && kitGood == null) {
      return res.status(400).json({ success: false, error: 'setSku або kitGood обовʼязкові' });
    }
    if (!Number.isFinite(resolvedKitQty) || resolvedKitQty <= 0) {
      return res.status(400).json({ success: false, error: 'kitQty має бути додатнім числом' });
    }

    const resolvedKitGood = await resolveKitGoodId(resolvedSetSku, kitGood as string | number | undefined);
    if (!resolvedKitGood) {
      return res.status(422).json({ success: false, error: 'Не вдалося визначити ID набору в Dilovod (kitGood)' });
    }

    const currentUserId = (req as any).user?.userId || (req as any).user?.id;
    const parsedDate = parseLocalDate(resolvedDate) ?? new Date();
    const formattedDate = formatLocalDate(parsedDate);
    const author = await getDilovodUserId(currentUserId, { logPrefix: '[SetRelease] ' }).catch(() => '');
    const dilovodConfig = await getDilovodConfigFromDB();
    const { loadDilovodWarehouseDefaults } = await import('../../services/dilovod/DilovodWarehouseDefaults.js');
    const warehouseDefaults = await loadDilovodWarehouseDefaults();
    const effectiveFirmId = (resolvedFirmIdInput != null && String(resolvedFirmIdInput).trim() !== '')
      ? String(resolvedFirmIdInput).trim()
      : (dilovodConfig.defaultFirmId ?? null);

    const expandedComponents = await collectFirstLevelComponents(items as ReleaseSetSourceItem[]);
    const batchValidation = validateReleaseBatches(
      expandedComponents,
      parsedComponentBatches,
      { requireBatches: requireBatches === true || requireBatches === 'true' },
    );

    if (!batchValidation.valid) {
      // raw лише для відповіді Dilovod — тут його немає (запит не йшов у API).
      const userMessage = batchValidation.errors[0] || 'Некоректний розподіл партій';
      const previous = extractSendErrorFromReleaseItems(retryRecord?.items);
      const sendError = buildReleaseSendError({
        message: userMessage,
        raw: previous?.source === 'dilovod' ? previous.raw : null,
        source: 'validation',
      });
      let errorPersisted = false;
      if (releaseId && retryRecord) {
        errorPersisted = await patchReleaseSendError(releaseId, retryRecord.items, sendError);
      }
      return res.status(422).json({
        success: false,
        error: userMessage,
        sendError,
        validation: batchValidation,
        errorPersisted,
        canRetry: Boolean(releaseId),
      });
    }

    let effectiveComponentBatches = [...parsedComponentBatches];
    let createdSurplusBatch: { batchId: string; batchNumber: string } | null = null;
    let kitOutputBatch: Awaited<ReturnType<typeof warehouseBatchesService.ensureKitOutputBatch>> | null = null;
    const surplusQty = Number(surplusQuantity ?? 0);
    const shouldCreateSurplus = createSurplusBatch === true || createSurplusBatch === 'true';

    if (shouldCreateSurplus && Number.isFinite(surplusQty) && surplusQty > 0) {
      const surplusGood = String(surplusGoodId ?? '').trim();
      if (!surplusGood) {
        return res.status(422).json({ success: false, error: 'surplusGoodId обовʼязковий для створення партії надлишку' });
      }

      createdSurplusBatch = await warehouseBatchesService.createCorrectionBatch({
        goodId: surplusGood,
        batchName: formatCorrectionBatchName(parsedDate),
      });

      const surplusSku = Object.values(expandedComponents)[0]?.sku;
      if (surplusSku) {
        const existingAllocation = effectiveComponentBatches.find((allocation) => allocation.sku === surplusSku);
        if (existingAllocation) {
          existingAllocation.batches.push({
            batchId: createdSurplusBatch.batchId,
            batchNumber: createdSurplusBatch.batchNumber,
            quantity: surplusQty,
          });
        } else {
          effectiveComponentBatches.push({
            sku: surplusSku,
            batches: [{
              batchId: createdSurplusBatch.batchId,
              batchNumber: createdSurplusBatch.batchNumber,
              quantity: surplusQty,
            }],
          });
        }
      }
    }

    const storedKitOutputBatch = retryRecord ? extractStoredKitOutputBatch(retryRecord.items) : null;
    if (isRegularKitRelease({
      operationType: resolvedOperationType,
      setSku: resolvedSetSku,
      correctionSessionId: resolvedCorrectionSessionId,
    })) {
      if (storedKitOutputBatch?.batchId && !isDryRun) {
        kitOutputBatch = {
          batchId: storedKitOutputBatch.batchId,
          batchNumber: storedKitOutputBatch.batchNumber,
          barcode: storedKitOutputBatch.barcode,
          created: false,
          expiration: storedKitOutputBatch.expiration,
        };
      } else {
        kitOutputBatch = await warehouseBatchesService.ensureKitOutputBatch({
          kitGoodId: resolvedKitGood,
          operDate: parsedDate,
          componentBatchIds: collectComponentBatchIds(effectiveComponentBatches),
          dryRun: isDryRun,
        });
      }
    }

    let docNumber: string;
    if (isDryRun) {
      docNumber = retryRecord?.internalDocNumber ?? await projectReleaseDocNumber();
    } else if (retryRecord) {
      docNumber = retryRecord.internalDocNumber ?? formatReleaseDocNumber(retryRecord.id);
    } else {
      const allocated = await allocateReleaseDocNumber({
        createdBy: Number(currentUserId) || 0,
        setSku: resolvedSetSku || null,
        quantity: resolvedKitQty,
        storageId: resolvedStorageId ?? null,
        firmId: effectiveFirmId,
        operationType: resolvedOperationType,
        operDate: parsedDate,
      });
      releaseId = allocated.releaseId;
      docNumber = allocated.docNumber;
    }

    const payload: any = {
      saveType: 1,
      header: {
        id: SET_RELEASE_DOC_ID,
        number: docNumber,
        date: formattedDate,
        firm: effectiveFirmId,
        storage: resolvedStorageId ?? null,
        posted: 1,
        accCosts: warehouseDefaults.setAccountId,
        docMode: resolvedDocMode,
        kitGood: resolvedKitGood,
        kitQty: resolvedKitQty,
        ...(kitOutputBatch?.batchId ? { kitGoodPart: Number(kitOutputBatch.batchId) } : {}),
        ...(author ? { author } : {}),
        ...((resolvedRemark || resolvedComment)
          ? { remark: String(resolvedRemark || resolvedComment).trim() }
          : {}),
      },
    };

    const exportWarnings = [...batchValidation.warnings];

    try {
      const expandedList = Object.values(expandedComponents);
      const skus = expandedList.map((component) => component.sku).filter(Boolean);
      const found = skus.length ? await catalogOpsLookup.getBySkus(skus) : new Map();
      const skuToProduct = new Map(catalogOpsLookup.listUnique(found).map((product) => [product.sku, product]));
      const skuToDilovodId = new Map<string, string>();
      const skuToHasNestedSet = new Map<string, boolean>();

      for (const [sku, product] of skuToProduct.entries()) {
        if (!product?.dilovodId) continue;
        skuToDilovodId.set(sku, product.dilovodId);
        const hasNestedSet = Array.isArray(product.set)
          ? product.set.length > 0
          : typeof product.set === 'string'
            ? String(product.set).trim().length > 0
            : Boolean(product.set);
        skuToHasNestedSet.set(sku, hasNestedSet);
      }

      const { tpGoods, warnings: tpWarnings } = buildTpGoodsFromBatches(
        expandedList,
        skuToDilovodId,
        skuToHasNestedSet,
        effectiveComponentBatches,
        warehouseDefaults,
      );
      exportWarnings.push(...tpWarnings);

      if (!payload.tableParts) payload.tableParts = {};
      payload.tableParts.tpGoods = tpGoods;
    } catch (e) {
      console.warn('[SetRelease] Failed to build tpGoods tablePart:', e);
    }

    const exportResult = await dilovodExportFlowService.send({
      payload,
      dryRun: dryRun === true || dryRun === 'true',
      warnings: exportWarnings,
      label: '[SetRelease]',
    });

    if (exportResult.dryRun) {
      return res.json(exportResult);
    }

    if (!exportResult.success) {
      const rawError = exportResult.error || exportResult.dilovodResponse?.error || exportResult.dilovodResponse?.message || 'Dilovod error';
      const translated = exportResult.translatedError ?? translateDilovodError(String(rawError));
      const technicalMessage = exportResult.dilovodResponse
        ? getDilovodExportErrorMessage(exportResult.dilovodResponse)
        : String(rawError);
      const sendError = buildReleaseSendError({
        message: translated.message || technicalMessage,
        raw: formatReleaseSendErrorRaw(exportResult.dilovodResponse, technicalMessage),
        source: 'dilovod',
      });

      let historySaved = false;
      if (!isDryRun && releaseId && items.length > 0) {
        const historyPayload = await prepareReleaseHistoryPayload({
          items,
          componentBatches: effectiveComponentBatches,
          remark: resolvedRemark,
          comment: resolvedComment,
          operationType: resolvedOperationType,
          operDate: resolvedDate,
          date: resolvedDate,
          correctionSessionId: resolvedCorrectionSessionId,
        });
        const dilovodRemark = String(resolvedRemark || resolvedComment || '').trim() || null;
        await persistFailedReleaseAttempt(releaseId, {
          historyPayload,
          storageId: resolvedStorageId ?? null,
          firmId: effectiveFirmId,
          sendError,
          kitOutputBatch,
          dilovodRemark,
        });
        historySaved = true;
      } else {
        await discardFailedReleasePlaceholder(releaseId);
      }

      return res.status(422).json({
        success: false,
        error: sendError.message,
        errorTitle: translated.title,
        errorFallback: translated.message,
        sendError,
        dilovodResponse: exportResult.dilovodResponse,
        docNumber,
        releaseId,
        historySaved,
        canRetry: historySaved,
      });
    }

    const stockSyncTriggered = true;

    void (async () => {
      try {
        const { syncSettingsService } = await import('../../services/syncSettingsService.js');
        const isEnabled = await syncSettingsService.isSyncEnabled('stocks');
        if (!isEnabled) {
          console.log('⏭️ [SetRelease] Stock sync після випуску пропущено — синхронізація залишків вимкнена');
          return;
        }

        console.log('🔄 [SetRelease] Запускаємо оновлення залишків після випуску набору...');
        const { DilovodService: DilovodServiceCls } = await import('../../services/dilovod/DilovodService.js');
        const stockService = new DilovodServiceCls();
        const result = await stockService.updateStockBalancesInDatabase();
        console.log('✅ [SetRelease] Залишки оновлено після випуску набору:', result?.message ?? 'OK');
      } catch (error) {
        console.warn('⚠️ [SetRelease] Не вдалось оновити залишки після випуску набору:', error);
      }
    })();

    let historySaved = false;
    if (!isDryRun && releaseId && items.length > 0) {
      const historyPayload = await prepareReleaseHistoryPayload({
        items,
        componentBatches: effectiveComponentBatches,
        remark: resolvedRemark,
        comment: resolvedComment,
        operationType: resolvedOperationType,
        operDate: resolvedDate,
        date: resolvedDate,
        correctionSessionId: resolvedCorrectionSessionId,
      });

      const dilovodRemark = String(resolvedRemark || resolvedComment || '').trim() || null;
      const itemsWithMeta = historyPayload.itemsWithNames.map((item, index) => {
        if (index !== 0) return item;
        return {
          ...item,
          dilovod_send_error: null,
          ...(kitOutputBatch ? { kit_output_batch: kitOutputBatch } : {}),
          ...(dilovodRemark ? { dilovod_remark: dilovodRemark } : {}),
        };
      });

      await finalizeReleaseRecord(releaseId, {
        ...historyPayload,
        itemsWithNames: itemsWithMeta,
        storageId: resolvedStorageId ?? null,
        firmId: effectiveFirmId,
        dilovodDocId: exportResult.dilovodDocId != null && String(exportResult.dilovodDocId).trim() !== ''
          ? String(exportResult.dilovodDocId).trim()
          : null,
        status: RELEASE_STATUS_CREATED,
      });
      historySaved = true;
    }

    return res.json({
      success: true,
      payload,
      dilovodResponse: exportResult.dilovodResponse,
      dilovodDocId: exportResult.dilovodDocId,
      docNumber,
      releaseId,
      historySaved,
      stockSyncTriggered,
      warnings: exportWarnings,
      createdSurplusBatch,
      kitOutputBatch,
      componentBatches: effectiveComponentBatches,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Internal server error';
    const sendError = buildReleaseSendError({
      message: 'Внутрішня помилка під час відправки в Dilovod. Спробуйте ще раз або зверніться до адміністратора.',
      raw: message,
      source: 'internal',
    });
    if (releaseId) {
      try {
        const itemsForSave = Array.isArray(req.body?.items) ? req.body.items : [];
        if (itemsForSave.length > 0) {
          const historyPayload = await prepareReleaseHistoryPayload({
            items: itemsForSave,
            componentBatches: parseComponentBatches(req.body?.componentBatches, {
              excludeAutoGenerated: shouldExcludeAutoGeneratedBatches(req.body?.correctionSessionId),
            }),
            remark: req.body?.remark,
            comment: req.body?.comment,
            operationType: req.body?.operationType,
            operDate: req.body?.date,
            date: req.body?.date,
            correctionSessionId: req.body?.correctionSessionId,
          });
          await persistFailedReleaseAttempt(releaseId, {
            historyPayload,
            storageId: req.body?.storageId ?? null,
            firmId: req.body?.firmId ?? null,
            sendError,
          });
        } else {
          await discardFailedReleasePlaceholder(releaseId);
        }
      } catch (persistError) {
        console.warn('[SetRelease] Failed to persist failed release attempt:', persistError);
        await discardFailedReleasePlaceholder(releaseId);
      }
    }
    console.error('[SetRelease] Error sending set release:', error);
    res.status(500).json({ success: false, error: sendError.message, sendError, releaseId });
  }
});

/** GET /api/warehouse/releases/last-kit-batches */
router.get('/last-kit-batches', authenticateToken, warehouseOperate, async (req, res) => {
  try {
    const setSku = String(req.query.setSku ?? '').trim();
    if (!setSku) {
      return res.status(400).json({ success: false, error: 'setSku required' });
    }

    const storageId = req.query.storageId != null && String(req.query.storageId).trim() !== ''
      ? String(req.query.storageId).trim()
      : undefined;
    const firmId = req.query.firmId != null && String(req.query.firmId).trim() !== ''
      ? String(req.query.firmId).trim()
      : undefined;

    const where: Record<string, unknown> = {
      operationType: 'kit',
      status: { not: 'deleted' },
      setSku,
    };
    if (storageId) where.storageId = storageId;
    if (firmId) where.firmId = firmId;

    let lastRecord = await prisma.warehouseReleaseSet.findFirst({
      where,
      orderBy: { createdAt: 'desc' },
    });

    if (!lastRecord && (storageId || firmId)) {
      lastRecord = await prisma.warehouseReleaseSet.findFirst({
        where: {
          operationType: 'kit',
          status: { not: 'deleted' },
          setSku,
        },
        orderBy: { createdAt: 'desc' },
      });
    }

    if (!lastRecord) {
      return res.json({
        success: true,
        data: {
          releaseId: null,
          dilovodDocId: null,
          operDate: null,
          componentBatches: [],
        },
      });
    }

    const operDate = lastRecord.operDate instanceof Date && !Number.isNaN(lastRecord.operDate.getTime())
      ? lastRecord.operDate.toISOString()
      : null;

    return res.json({
      success: true,
      data: {
        releaseId: lastRecord.id,
        dilovodDocId: lastRecord.dilovodDocId,
        operDate,
        componentBatches: extractComponentBatchesFromReleaseRecord(lastRecord),
      },
    });
  } catch (error) {
    console.error('[SetRelease] Error fetching last kit batches:', error);
    return res.status(500).json({ success: false, error: 'Internal server error' });
  }
});

/** GET /api/warehouse/releases/batch-correction/search-sets?q= */
router.get('/batch-correction/search-sets', authenticateToken, warehouseOperate, async (req, res) => {
  try {
    const query = String(req.query.q ?? req.query.search ?? '').trim();
    if (query.length < 3) {
      return res.json({ success: true, products: [] });
    }

    const products = await productsCatalogService.searchInventoryRebatchSets(query);
    return res.json({ success: true, products });
  } catch (error) {
    console.error('[SetRelease] batch-correction search-sets error:', error);
    return res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : 'Internal server error',
    });
  }
});

/** POST /api/warehouse/releases/kit-output-batch/preview */
router.post('/kit-output-batch/preview', authenticateToken, warehouseOperate, async (req, res) => {
  try {
    const setSku = String(req.body?.setSku ?? '').trim();
    const kitGood = req.body?.kitGood;
    const parsedDate = parseLocalDate(req.body?.date) ?? new Date();
    const parsedComponentBatches = parseComponentBatches(req.body?.componentBatches);
    const correctionSessionId = req.body?.correctionSessionId;

    if (!setSku && kitGood == null) {
      return res.status(400).json({ success: false, error: 'setSku або kitGood обовʼязкові' });
    }

    const resolvedKitGood = await resolveKitGoodId(setSku, kitGood as string | number | undefined);
    if (!resolvedKitGood) {
      return res.status(422).json({ success: false, error: 'Не вдалося визначити ID набору в Dilovod (kitGood)' });
    }

    if (!isRegularKitRelease({
      operationType: 'kit',
      setSku,
      correctionSessionId,
    })) {
      return res.json({ success: true, data: null });
    }

    const preview = await warehouseBatchesService.ensureKitOutputBatch({
      kitGoodId: resolvedKitGood,
      operDate: parsedDate,
      componentBatchIds: collectComponentBatchIds(parsedComponentBatches),
      dryRun: true,
    });

    return res.json({ success: true, data: preview });
  } catch (error) {
    console.error('[SetRelease] kit-output-batch preview error:', error);
    return res.status(422).json({
      success: false,
      error: error instanceof Error ? error.message : 'Internal server error',
    });
  }
});

/** POST /api/warehouse/releases/batch-correction/ensure-set */
router.post('/batch-correction/ensure-set', authenticateToken, warehouseOperate, async (req, res) => {
  try {
    const sourceSku = String(req.body?.sourceSku ?? '').trim();
    if (!sourceSku) {
      return res.status(400).json({ success: false, error: 'sourceSku required' });
    }

    const result = await productsCatalogService.ensureInventorySetForSku(sourceSku);
    return res.json({ success: true, data: result });
  } catch (error) {
    console.error('[SetRelease] ensure-set error:', error);
    return res.status(422).json({
      success: false,
      error: error instanceof Error ? error.message : 'Internal server error',
    });
  }
});

/** POST /api/warehouse/releases/batch-correction/fill-batches */
router.post('/batch-correction/fill-batches', authenticateToken, warehouseOperate, async (req, res) => {
  try {
    const sku = String(req.body?.sku ?? '').trim();
    if (!sku) {
      return res.status(400).json({ success: false, error: 'sku required' });
    }

    const storageId = req.body?.storageId != null && String(req.body.storageId).trim() !== ''
      ? String(req.body.storageId).trim()
      : undefined;
    const firmId = req.body?.firmId != null && String(req.body.firmId).trim() !== ''
      ? String(req.body.firmId).trim()
      : undefined;
    const parsedDate = parseLocalDate(req.body?.asOfDate ?? req.body?.date);

    const { dilovodService } = await import('../../services/dilovod/DilovodService.js');
    const dilovodConfig = await getDilovodConfigFromDB();
    const effectiveFirmId = firmId ?? dilovodConfig.defaultFirmId ?? undefined;

    const rawBatches = await dilovodService.getBatchNumbersBySku(sku, effectiveFirmId, parsedDate ?? undefined, {
      includeNonPositiveQty: false,
    });

    const batches: ReleaseComponentBatch[] = dedupeBatchesByStorage(rawBatches)
      .filter((batch) => !storageId || String(batch.storage ?? '') === storageId)
      .filter((batch) => Number(batch.quantity ?? 0) > 0)
      .map((batch) => ({
        batchId: String(batch.batchId ?? '').trim(),
        batchNumber: String(batch.batchNumber ?? batch.batchId ?? '').trim(),
        quantity: Number(batch.quantity ?? 0),
      }))
      .filter((batch) => batch.batchId && batch.quantity > 0);

    const totalQuantity = batches.reduce((sum, batch) => sum + batch.quantity, 0);

    return res.json({
      success: true,
      data: {
        sku,
        batches,
        totalQuantity,
        batchCount: batches.length,
      },
    });
  } catch (error) {
    console.error('[SetRelease] fill-batches error:', error);
    return res.status(500).json({ success: false, error: error instanceof Error ? error.message : 'Internal server error' });
  }
});

/** GET /api/warehouse/releases */
router.get('/', authenticateToken, async (req, res) => {
  try {
    if (process.env.NODE_ENV === 'development') console.log('[SetRelease][get] user:', (req as any).user, 'query:', req.query);

    const page = Math.max(1, Number(req.query.page) || 1);
    const limit = Math.min(100, Math.max(1, Number(req.query.limit) || 10));
    const statusFilter = String(req.query.status ?? 'active').toLowerCase() === 'deleted' ? 'deleted' : 'active';
    const where = statusFilter === 'deleted'
      ? { status: 'deleted' }
      : { status: { in: RELEASE_ACTIVE_STATUSES } };

    const [total, rows] = await Promise.all([
      prisma.warehouseReleaseSet.count({ where }),
      prisma.warehouseReleaseSet.findMany({
        where,
        orderBy: { createdAt: 'desc' },
        skip: (page - 1) * limit,
        take: limit,
      }),
    ]);

    const withNormalized = rows.map((record: any) => ({
      ...record,
      setsNormalized: normalizeSetsArray(record.items),
    }));

    res.json({
      success: true,
      data: withNormalized,
      pagination: {
        page,
        limit,
        total,
        pages: Math.max(1, Math.ceil(total / limit)),
      },
    });
  } catch (error) {
    console.error('[SetRelease] Error fetching releases:', error);
    res.status(500).json({ success: false, error: 'Internal server error' });
  }
});

/** GET /api/warehouse/releases/:id/audit */
router.get('/:id/audit', authenticateToken, warehouseOperate, async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id) || id <= 0) {
      return res.status(400).json({ success: false, error: 'Invalid id' });
    }
    const existing = await prisma.warehouseReleaseSet.findUnique({ where: { id } });
    if (!existing || existing.status === 'deleted') {
      return res.status(404).json({ success: false, error: 'Not found' });
    }
    const logs = await warehouseReleaseAuditService.list(id);
    return res.json({ success: true, data: logs });
  } catch (error) {
    console.error('[SetRelease] audit list error:', error);
    return res.status(500).json({ success: false, error: 'Internal server error' });
  }
});

/** PATCH /api/warehouse/releases/:id — редагування запису + синхронізація з Dilovod */
router.patch('/:id', authenticateToken, warehouseOperate, async (req, res) => {
  try {
    const id = Number(req.params.id);
    if (!Number.isFinite(id) || id <= 0) {
      return res.status(400).json({ success: false, error: 'Invalid id' });
    }

    const existing = await prisma.warehouseReleaseSet.findUnique({ where: { id } });
    if (!existing || existing.status === 'deleted') {
      return res.status(404).json({ success: false, error: 'Not found' });
    }
    if (existing.status !== RELEASE_STATUS_CREATED && existing.status !== RELEASE_STATUS_SEND_FAILED) {
      return res.status(422).json({ success: false, error: 'Редагувати можна лише активні операції комплектування' });
    }

    assertCanEditReleaseRecord(req, existing);

    const bodyItems = Array.isArray(req.body?.items) ? req.body.items : null;
    const fullSnapshot = Boolean(bodyItems && bodyItems.length > 0);
    const userId = Number((req as any).user?.userId || (req as any).user?.id) || null;

    let nextOperDate = req.body?.operDate != null
      ? (parseLocalDate(req.body.operDate) ?? parseLocalDate(req.body?.date) ?? existing.operDate)
      : (parseLocalDate(req.body?.date) ?? existing.operDate);
    let nextComment = req.body?.comment !== undefined
      ? (req.body.comment == null || String(req.body.comment).trim() === '' ? null : String(req.body.comment).trim())
      : existing.comment;
    let nextQuantity = req.body?.quantity != null
      ? Math.max(0, Math.trunc(Number(req.body.quantity)))
      : existing.quantity;
    let nextSetSku = req.body?.setSku !== undefined
      ? (req.body.setSku == null || String(req.body.setSku).trim() === '' ? null : String(req.body.setSku).trim())
      : existing.setSku;
    let nextStorageId = existing.storageId;
    let nextFirmId = existing.firmId;
    let nextOperationType = existing.operationType;
    let nextItems: any[] = Array.isArray(existing.items) ? [...existing.items] : [];
    let parsedBatches: ReturnType<typeof parseComponentBatches> = [];

    if (fullSnapshot && bodyItems) {
      parsedBatches = parseComponentBatches(req.body?.componentBatches, {
        excludeAutoGenerated: shouldExcludeAutoGeneratedBatches(req.body?.correctionSessionId),
      });
      const historyPayload = await prepareReleaseHistoryPayload({
        items: bodyItems,
        componentBatches: parsedBatches,
        remark: req.body?.remark,
        comment: req.body?.comment,
        operationType: req.body?.operationType ?? existing.operationType,
        operDate: req.body?.operDate ?? req.body?.date ?? existing.operDate,
        correctionSessionId: req.body?.correctionSessionId,
      });
      nextOperDate = historyPayload.resolvedOperDate;
      nextComment = historyPayload.historyComment;
      nextQuantity = historyPayload.totalQuantity;
      nextSetSku = historyPayload.setSku;
      nextOperationType = historyPayload.resolvedOperationType;
      nextStorageId = req.body?.storageId != null && String(req.body.storageId).trim() !== ''
        ? String(req.body.storageId).trim()
        : existing.storageId;
      nextFirmId = req.body?.firmId != null && String(req.body.firmId).trim() !== ''
        ? String(req.body.firmId).trim()
        : existing.firmId;
      nextItems = preserveReleaseItemMeta(existing.items, historyPayload.itemsWithNames);
      if (nextItems[0] && typeof nextItems[0] === 'object') {
        (nextItems[0] as Record<string, unknown>).component_batches = parsedBatches;
      }
    }

    const before = {
      operDate: existing.operDate,
      comment: existing.comment,
      quantity: existing.quantity,
      setSku: existing.setSku,
      batches: summarizeReleaseBatches(existing.items),
      storageId: existing.storageId,
      firmId: existing.firmId,
    };
    const after = {
      operDate: nextOperDate,
      comment: nextComment,
      quantity: nextQuantity,
      setSku: nextSetSku,
      batches: summarizeReleaseBatches(nextItems),
      storageId: nextStorageId,
      firmId: nextFirmId,
    };
    const changes = buildReleaseUpdateDiff(before, after);
    if (changes.length === 0 && nextOperationType === existing.operationType) {
      return res.json({ success: true, data: existing, unchanged: true });
    }

    const editorLabel = await getReleaseEditorLabel(userId);
    const remarkNote = buildWarehouseReleaseEditRemarkNote(editorLabel, changes);

    if (!fullSnapshot && nextItems[0] && typeof nextItems[0] === 'object') {
      nextItems[0] = {
        ...(nextItems[0] as Record<string, unknown>),
        quantity: nextQuantity,
        set_sku: nextSetSku,
        setSku: nextSetSku,
      };
    }

    if (existing.status === RELEASE_STATUS_CREATED && existing.dilovodDocId) {
      const syncItems = fullSnapshot && bodyItems
        ? bodyItems.map((item: any, index: number) => (
          index === 0
            ? {
              ...item,
              component_batches: parsedBatches,
              ...(Array.isArray(existing.items) && existing.items[0] && typeof existing.items[0] === 'object'
                ? { kit_output_batch: (existing.items[0] as { kit_output_batch?: unknown }).kit_output_batch }
                : {}),
            }
            : item
        ))
        : nextItems;
      const syncResult = await syncWarehouseReleaseToDilovod({
        record: {
          ...existing,
          items: syncItems,
          storageId: nextStorageId,
          firmId: nextFirmId,
          operationType: nextOperationType,
        },
        operDate: nextOperDate,
        quantity: nextQuantity,
        setSku: nextSetSku,
        remarkNote,
      });
      if (!syncResult.success) {
        return res.status(422).json({ success: false, error: syncResult.error || 'Не вдалося оновити документ у Dilovod' });
      }
      if (syncResult.remark && nextItems[0] && typeof nextItems[0] === 'object') {
        nextItems[0] = {
          ...(nextItems[0] as Record<string, unknown>),
          dilovod_remark: syncResult.remark,
        };
      }
    }

    const updated = await prisma.warehouseReleaseSet.update({
      where: { id },
      data: {
        operDate: nextOperDate,
        comment: nextComment,
        quantity: nextQuantity,
        setSku: nextSetSku,
        storageId: nextStorageId,
        firmId: nextFirmId,
        operationType: nextOperationType,
        items: nextItems,
      },
    });

    await warehouseReleaseAuditService.log({
      releaseId: id,
      action: 'release_updated',
      userId,
      payload: { changes } as Prisma.InputJsonValue,
    });

    return res.json({ success: true, data: updated });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Internal server error';
    const status = message.includes('недоступне') ? 403 : 500;
    console.error('[SetRelease] patch release error:', error);
    return res.status(status).json({ success: false, error: message });
  }
});

/** DELETE /api/warehouse/releases/:id */
router.delete('/:id', authenticateToken, warehouseHistoryDelete, async (req, res) => {
  try {
    const id = Number(req.params.id);
    const existing = await prisma.warehouseReleaseSet.findUnique({ where: { id } });
    if (!existing) return res.status(404).json({ success: false, error: 'Not found' });

    const { forceLocal } = req.query;
    if (String(forceLocal) === 'true') {
      await prisma.warehouseReleaseSet.update({ where: { id }, data: { status: 'deleted' } });
      return res.json({ success: true });
    }

    const releaseDocId = existing.dilovodDocId != null ? String(existing.dilovodDocId).trim() : '';
    if (releaseDocId) {
      try {
        const payload: any = { saveType: 2, header: { id: releaseDocId, delMark: 1 } };
        const exportResult = await dilovodExportFlowService.send({ payload, dryRun: false, warnings: [], label: '[SetRelease]' });
        const result = exportResult.dilovodResponse;

        if (!exportResult.success) {
          const msg = String(exportResult.error || result?.error || result?.message || 'Unknown error');
          if (msg.toLowerCase().includes('not found') || msg.toLowerCase().includes('object with id') || msg.toLowerCase().includes('не знайдено') || msg.toLowerCase().includes('не знайден')) {
            return res.status(422).json({ success: false, error: msg, canDeleteLocal: true });
          }
          return res.status(422).json({ success: false, error: msg });
        }
      } catch (err) {
        console.warn('[SetRelease] Error deleting in Dilovod:', err);
        return res.status(500).json({ success: false, error: 'Error deleting in Dilovod', details: err instanceof Error ? err.message : String(err) });
      }
    }

    await prisma.warehouseReleaseSet.update({ where: { id }, data: { status: 'deleted' } });
    res.json({ success: true });
  } catch (error) {
    console.error('[SetRelease] Error deleting release:', error);
    res.status(500).json({ success: false, error: 'Internal server error' });
  }
});

export default router;
