import type { ReturnBatch } from '../WarehouseReturns/WarehouseReturnsTypes';
import { canSetTpGoodsGoodPart, isAutoGeneratedSystemBatch } from '@shared/utils/dilovodBatchId';

/** Партії, придатні для tpGoods.goodPart (без віртуальних і системних). */
export function filterWarehouseSelectableBatches(batches: ReturnBatch[]): ReturnBatch[] {
  return batches.filter((batch) => {
    const batchId = String(batch.batchId ?? '').trim();
    if (batchId.startsWith('virtual:')) return false;
    const label = String(batch.batchNumber ?? batch.batchId ?? '').trim();
    if (isAutoGeneratedSystemBatch(label)) return false;
    return canSetTpGoodsGoodPart({ batchId: batch.batchId, batchNumber: batch.batchNumber });
  });
}
